//! AWS Signature Version 4, for the S3 provider. P2-001.
//!
//! The one thing S3 needs that nothing else in this workspace had, and the
//! reason `s3` was a target kind this build refused. P1-005 hit the same wall
//! from the other side and recorded it: R2's temporary access credentials yield
//! SigV4 credentials, and a transport that can only send a bearer token cannot
//! spend them.
//!
//! # Where the algorithm comes from, and where the test values come from
//!
//! The construction is AWS's *Signature Version 4 signing process*: a canonical
//! request, a string to sign over it, a signing key derived by four chained
//! HMACs, and an `Authorization` header naming the credential scope and the
//! signed headers.
//!
//! **No constant in the tests beside this file was written from memory.** They
//! were generated by `botocore` 1.43.71's `S3SigV4Auth` on the machine this was
//! written on, with a pinned timestamp, by the script kept at the top of
//! `tests.rs`. That matters more than it sounds: a signer that is wrong in a
//! way that still produces a stable string passes every test that compares it
//! with itself, and fails only against a real S3 — which this repository has no
//! account for and would not call from a test if it had. An independent
//! implementation is the only thing that can say the answer is right.
//!
//! The loopback double in `tests/test-apex-backup-s3.sh` recomputes the whole
//! signature in Python with `hmac` and `hashlib` and answers **403** when it
//! does not match, so the end-to-end path is checked by a second independent
//! implementation as well.
//!
//! # What this signs, and what it deliberately does not
//!
//! Three headers: `host`, `x-amz-content-sha256` and `x-amz-date`. That is the
//! minimum S3 accepts and it is all this build sends that matters — the
//! `User-Agent` and `Accept` curl adds are not signed, which is allowed:
//! `SignedHeaders` says exactly which were, and a header outside that list
//! cannot change the signature or be relied upon by the far side.
//!
//! **The payload is always signed**, never `UNSIGNED-PAYLOAD`. botocore will
//! skip payload signing for a streaming upload over https; this build has the
//! bytes in hand either way, so there is nothing to gain by weakening it.
//!
//! # The canonical URI and query are the caller's, already encoded
//!
//! [`Request::canonical_uri`] is compared byte for byte with the path in the
//! URL, so a signer that re-encoded it would sign something other than what is
//! sent, and one that decoded it would differ from what S3 canonicalises. So
//! the caller builds the path once, and the same string goes into the URL and
//! into the signature. [`encode_path`] is the encoder it should use.

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};

type HmacSha256 = Hmac<Sha256>;

/// `AWS4-HMAC-SHA256`.
pub const ALGORITHM: &str = "AWS4-HMAC-SHA256";

/// The three headers this build signs, lowercase and already in order.
pub const SIGNED_HEADERS: &str = "host;x-amz-content-sha256;x-amz-date";

/// One request, in the form the signature is computed over.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Request<'a> {
    /// `GET`, `PUT`. Uppercase.
    pub method: &'a str,
    /// The `Host` header exactly as it will be sent, port included when it is
    /// not the scheme's default — because that is the byte string the far side
    /// will canonicalise.
    pub host: &'a str,
    /// The path, percent-encoded, starting with `/`. See [`encode_path`].
    pub canonical_uri: &'a str,
    /// The query string, encoded and sorted by parameter name, or empty.
    pub canonical_query: &'a str,
    /// Lowercase hex SHA-256 of the body. [`EMPTY_PAYLOAD_SHA256`] for none.
    pub payload_sha256: &'a str,
    /// `YYYYMMDDTHHMMSSZ`, UTC.
    pub amz_date: &'a str,
    pub region: &'a str,
}

/// SHA-256 of zero bytes, which every GET carries.
pub const EMPTY_PAYLOAD_SHA256: &str =
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

/// Lowercase hex SHA-256 of some bytes.
pub fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex(&hasher.finalize())
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push_str(&format!("{b:02x}"));
    }
    out
}

fn hmac(key: &[u8], data: &[u8]) -> Vec<u8> {
    // `new_from_slice` only fails for a key length no HMAC accepts, and
    // HMAC-SHA256 accepts every length — the construction hashes a long key
    // and pads a short one. Written as an expect rather than a `?` so that no
    // caller has to carry an error that cannot happen.
    let mut mac = HmacSha256::new_from_slice(key).expect("HMAC accepts a key of any length");
    mac.update(data);
    mac.finalize().into_bytes().to_vec()
}

impl Request<'_> {
    /// `YYYYMMDD` — the date half of [`Request::amz_date`].
    ///
    /// Taken from the timestamp rather than computed a second time, because a
    /// signer that asked the clock twice could straddle midnight and sign a
    /// scope that does not match the date header it sent.
    pub fn date_stamp(&self) -> &str {
        self.amz_date.split('T').next().unwrap_or(self.amz_date)
    }

    /// `<date>/<region>/s3/aws4_request`.
    pub fn scope(&self) -> String {
        format!("{}/{}/s3/aws4_request", self.date_stamp(), self.region)
    }

    /// The canonical request, as AWS defines it.
    ///
    /// Public so a test can compare it with botocore's, which is how a wrong
    /// signature gets localised to the line that is wrong rather than to "the
    /// hex differs".
    pub fn canonical(&self) -> String {
        format!(
            "{}\n{}\n{}\nhost:{}\nx-amz-content-sha256:{}\nx-amz-date:{}\n\n{}\n{}",
            self.method,
            self.canonical_uri,
            self.canonical_query,
            self.host,
            self.payload_sha256,
            self.amz_date,
            SIGNED_HEADERS,
            self.payload_sha256
        )
    }

    /// The string the signing key is applied to.
    pub fn string_to_sign(&self) -> String {
        format!(
            "{ALGORITHM}\n{}\n{}\n{}",
            self.amz_date,
            self.scope(),
            sha256_hex(self.canonical().as_bytes())
        )
    }

    /// The signing key: four chained HMACs, date then region then service then
    /// the terminator.
    ///
    /// This is what makes a SigV4 signature scoped — a key derived for one day,
    /// one region and one service cannot sign for another — and it is the part
    /// a hand-rolled signer most often gets subtly wrong by reusing the secret
    /// directly.
    fn signing_key(&self, secret: &str) -> Vec<u8> {
        let k_date = hmac(format!("AWS4{secret}").as_bytes(), self.date_stamp().as_bytes());
        let k_region = hmac(&k_date, self.region.as_bytes());
        let k_service = hmac(&k_region, b"s3");
        hmac(&k_service, b"aws4_request")
    }

    /// The signature, lowercase hex.
    pub fn signature(&self, secret: &str) -> String {
        hex(&hmac(
            &self.signing_key(secret),
            self.string_to_sign().as_bytes(),
        ))
    }

    /// The whole `Authorization` header value.
    pub fn authorization(&self, access_key_id: &str, secret: &str) -> String {
        format!(
            "{ALGORITHM} Credential={access_key_id}/{}, SignedHeaders={SIGNED_HEADERS}, \
             Signature={}",
            self.scope(),
            self.signature(secret)
        )
    }
}

/// Percent-encode a path for both the URL and the canonical URI.
///
/// AWS's rule for S3: encode every byte that is not unreserved
/// (`A-Z a-z 0-9 - _ . ~`), and **do not encode the `/` separators**, and **do
/// not encode twice**. S3 is the one service that does not double-encode the
/// path, which is exactly the detail a signer written from the general SigV4
/// description gets wrong.
///
/// Every object key this build produces is made of `operation::valid_name`
/// segments, so nothing it writes needs encoding at all. This exists for the
/// bucket and prefix a project may name, and so that the URL and the signature
/// are built by one function rather than two that agree until they do not.
pub fn encode_path(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    for byte in path.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' | b'/' => {
                out.push(byte as char)
            }
            other => out.push_str(&format!("%{other:02X}")),
        }
    }
    out
}

/// Percent-encode one query parameter name or value.
///
/// The same rule as [`encode_path`] **without** the `/` exception: a slash in a
/// query value is data and is encoded, which is why `prefix=apex-backup/`
/// signs as `prefix=apex-backup%2F`.
pub fn encode_query_component(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for byte in value.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            other => out.push_str(&format!("%{other:02X}")),
        }
    }
    out
}

/// `YYYYMMDDTHHMMSSZ` for a Unix timestamp in seconds.
///
/// Written out rather than taken from a date library, because this daemon has
/// none and the format is fixed. The civil-from-days conversion is Howard
/// Hinnant's, which is exact for every day in the proleptic Gregorian calendar
/// and has no leap-second or timezone behaviour to be surprised by — UTC is the
/// only thing SigV4 accepts.
pub fn amz_date(unix_secs: u64) -> String {
    let days = (unix_secs / 86_400) as i64;
    let secs_of_day = unix_secs % 86_400;
    let (year, month, day) = civil_from_days(days);
    format!(
        "{year:04}{month:02}{day:02}T{:02}{:02}{:02}Z",
        secs_of_day / 3600,
        (secs_of_day % 3600) / 60,
        secs_of_day % 60
    )
}

fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    (if m <= 2 { y + 1 } else { y }, m, d)
}

#[cfg(test)]
mod tests;
