//! §13.1: what this project's Cloudflare names mean.
//!
//! The semantic half of the provider. `my-worker` is not a string the broker
//! passes through — it is a name this project has to have bound to an account
//! and an environment, or the request does not happen. `example.com` is a zone
//! or it is nothing. That is what §13.2 means by *semantic operations, not one
//! broad "Cloudflare write" permission*: the grant says which verb, and the
//! binding says which thing.
//!
//! ```toml
//! [identity.cloudflare]
//! account = "example-account"
//! account_id = "0123456789abcdef0123456789abcdef"
//!
//! [cloudflare]
//! zone = "example.com"
//! zone_id = "fedcba9876543210fedcba9876543210"
//! buckets = ["example-assets"]
//!
//! [cloudflare.preview]
//! worker = "project-preview"
//!
//! [cloudflare.production]
//! worker = "project"
//! ```
//!
//! §13.1's own example carries `account`, `zone` and a `worker` per
//! environment. The two `_id` keys are here because of a constraint P1-001
//! imposes and §13.1 could not have known about: [`crate::provider::Provider::bind`]
//! **must not use a credential**, and Cloudflare's REST API addresses accounts
//! and zones by 32-hex id, not by name. Turning `example-account` into an id is
//! an authenticated `GET /accounts` — which is an operation in its own right
//! (`cloudflare.account.read`), not a step hidden inside another one. So the
//! id lives in the file, the name lives beside it for the people who read the
//! file, and `apex cf status` is what fills the id in.
//!
//! ## Why a refusal here names what *is* bound
//!
//! An agent that asked to deploy `staging` and was told "no" learns nothing it
//! can act on. Every refusal in this module names the file, the thing that was
//! asked for, and the things this project actually binds — because the fix is
//! always a line in that file, and the person reading the message is usually
//! the one who has to write it.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use apex_secret_core::operation;
use apex_secret_core::project::{ProjectConfig, ProjectError};

/// Length of a Cloudflare account or zone id.
const ID_LEN: usize = 32;

/// The shape an id has.
///
/// Four shapes and not one, because Cloudflare uses four, and every one of them
/// is interpolated into a URL path. Account, zone, KV namespace, queue,
/// Hyperdrive config, Secrets Store and DNS record ids are 32 lower-case hex; a
/// **D1 database id is a UUID** with hyphens, and `wrangler` calls the field
/// `db.uuid` for that reason; a tunnel is a UUID; an **Access application is
/// either**, which is the API's own `oneOf`; and an **AI Gateway id is a slug
/// the account chose**. A single validator would either refuse every real D1 id
/// or accept 36 characters of anything in a path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IdShape {
    /// 32 lower-case hex characters.
    Hex32,
    /// `8-4-4-4-12` lower-case hex.
    Uuid,
    /// Either of the two above.
    ///
    /// Not a convenience: Cloudflare's own schema says an Access application is
    /// addressed by `oneOf [identifier, uuid]`, because applications created
    /// before and after a migration carry different shapes. A validator that
    /// picked one would refuse half the real ids in existence.
    Hex32OrUuid,
    /// A lower-case slug, `^[a-z0-9_]+(?:-[a-z0-9_]+)*$`, 1 to 64 characters.
    ///
    /// An AI Gateway's id is not generated by Cloudflare at all — the account
    /// chooses it, and Cloudflare's schema carries exactly that pattern. It is
    /// still checked as strictly as the generated shapes, for the same reason:
    /// it is interpolated into a URL path.
    ///
    Slug,
    /// A Workers AI model name: `@cf/meta/llama-3.1-8b-instruct`.
    ///
    /// The schema gives `model_name` no pattern at all, so this is written from
    /// the documented shape rather than copied from one: an `@`, then
    /// `/`-separated segments of letters, digits, `.`, `_` and `-`. It is the
    /// only id here that starts with a character `operation::valid_name` would
    /// refuse, which is precisely why a model has to be bound rather than
    /// named.
    Model,
}

impl IdShape {
    pub fn accepts(&self, id: &str) -> bool {
        match self {
            IdShape::Hex32 => valid_id(id),
            IdShape::Uuid => valid_uuid(id),
            IdShape::Hex32OrUuid => valid_id(id) || valid_uuid(id),
            IdShape::Slug => valid_slug(id),
            IdShape::Model => valid_model(id),
        }
    }

    pub fn describe(&self) -> &'static str {
        match self {
            IdShape::Hex32 => "32 hexadecimal characters",
            IdShape::Uuid => "a UUID, like 1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d",
            IdShape::Hex32OrUuid => {
                "32 hexadecimal characters, or a UUID like \
                 1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d"
            }
            IdShape::Slug => {
                "a lower-case slug of letters, digits and '_', with '-' between \
                 groups, like my-gateway"
            }
            IdShape::Model => "a model name, like @cf/meta/llama-3.1-8b-instruct",
        }
    }
}

/// The `[cloudflare.<table>]` tables a project may bind, and the id shape each
/// one's values have to be.
///
/// These names are reserved: an environment may not be called one of them, or
/// `[cloudflare.kv]` would mean two things at once. See
/// [`BindingError::ReservedSection`].
pub const RESOURCES: &[(&str, IdShape, &str)] = &[
    ("d1", IdShape::Uuid, "D1 database"),
    ("kv", IdShape::Hex32, "KV namespace"),
    ("queues", IdShape::Hex32, "queue"),
    ("hyperdrive", IdShape::Hex32, "Hyperdrive config"),
    // §13.10's two. Same answer as the four above — the project writes the
    // name down next to the id — and for tunnels it is the ONLY answer
    // available: a Cloudflare Tunnel is addressed by an id that does not exist
    // until the tunnel does, so unlike an R2 bucket it cannot be named into
    // existence. Creating one is therefore not an operation this build offers;
    // the owner creates the tunnel and writes its id here.
    ("access", IdShape::Hex32OrUuid, "Access application"),
    ("tunnels", IdShape::Uuid, "tunnel"),
    // §13.6's. A store and not a secret: the secrets inside it are named, not
    // bound, because a project creates them and a file listing every secret it
    // will ever make could not be written in advance. The STORE is the boundary
    // — this project's operations reach the secrets in the stores its own file
    // lists and no others.
    ("secrets", IdShape::Hex32, "Secrets Store store"),
    // §13.11's two. The model table is the one that looks unnecessary and is
    // not: `@cf/meta/llama-3.1-8b-instruct` cannot be a `Syntax::Name` — the
    // grammar wants an alphanumeric first character — so a model could not be
    // named as a resource even if this build wanted the agent to choose one.
    // Binding it is the only way, and it is also the right way: §13.14's cost
    // guardrails start with the owner deciding which models a project may run.
    ("gateways", IdShape::Slug, "AI Gateway"),
    ("models", IdShape::Model, "model"),
];

/// What one of those tables says about a name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Resource {
    pub account: Account,
    /// What the project calls it.
    pub name: String,
    /// What the API is addressed by.
    pub id: String,
}

/// What a project binds.
#[derive(Debug, Clone, Default)]
pub struct Binding {
    /// The file it came from. Named in every refusal.
    pub path: PathBuf,
    /// `[identity.cloudflare] account` — the human label. Never sent anywhere.
    pub account: Option<String>,
    /// `[identity.cloudflare] account_id` — what the API is addressed by.
    pub account_id: Option<String>,
    /// `[cloudflare] zone`.
    pub zone: Option<String>,
    /// `[cloudflare] zone_id`.
    pub zone_id: Option<String>,
    /// `[cloudflare] buckets` — R2, so P1-005's. Resolvable now so that the
    /// meaning of a name is decided in one place rather than per task.
    pub buckets: Vec<String>,
    /// Every `[cloudflare.<table>]` in [`RESOURCES`], keyed by table name. Each
    /// holds `<name> = "<id>"`, because all of them are addressed by an id the
    /// project has to write down: unlike an R2 bucket, none of them has a
    /// name-based path, and unlike an account id, there is more than one per
    /// project.
    pub resources: BTreeMap<String, BTreeMap<String, String>>,
    /// `[cloudflare] records` — §13.9's narrowing, P1-007's. Empty means the
    /// bound zone and nothing narrower; a non-empty list means these names and
    /// no others, apex included only if it is written down.
    pub records: Vec<String>,
    /// `[cloudflare.<name>] worker`, by environment name.
    pub environments: BTreeMap<String, String>,
}

/// Why a name did not resolve.
///
/// Separate from [`ProjectError`] because these are all the same shape — *this
/// project does not bind that* — and they all have the same fix.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BindingError {
    /// The project file could not be read or parsed.
    Project(ProjectError),
    /// No `[identity.cloudflare]` at all.
    Unbound { path: PathBuf },
    /// A key that has to be an id is not one of the right shape.
    BadId { path: PathBuf, key: String },
    /// A resource is written down under a name no request could ever carry.
    BadName {
        path: PathBuf,
        table: String,
        named: String,
    },
    /// The account id is missing, so nothing can be addressed.
    NoAccount { path: PathBuf, account: Option<String> },
    /// No worker in any environment answers to that name.
    NoWorker {
        path: PathBuf,
        named: String,
        bound: Vec<String>,
    },
    /// That is not this project's zone.
    NoZone {
        path: PathBuf,
        named: String,
        bound: Option<String>,
    },
    /// That is not one of this project's buckets.
    NoBucket {
        path: PathBuf,
        named: String,
        bound: Vec<String>,
    },
    /// That is not a record this project may act on: either it is not inside
    /// the bound zone at all, or the project narrowed itself to a list that
    /// does not hold it.
    NoRecord {
        path: PathBuf,
        named: String,
        zone: String,
        bound: Vec<String>,
    },
    /// That is not one of this project's databases, namespaces, queues or
    /// Hyperdrive configs. One variant for the four, because the answer has the
    /// same shape every time and so does the fix.
    NoResource {
        path: PathBuf,
        /// The table it would have been in — `d1`, `kv`, `queues`,
        /// `hyperdrive`.
        table: String,
        /// What to call that kind of thing in a sentence.
        kind: String,
        named: String,
        bound: Vec<String>,
    },
    /// An environment is named after one of the reserved resource tables, so
    /// `[cloudflare.kv]` would have to mean two things at once.
    ReservedSection { path: PathBuf, name: String },
    /// The zone is named but its id is not, so a zone-scoped call cannot be
    /// addressed.
    NoZoneId { path: PathBuf, zone: String },
}

/// `a, b and c`, or `nothing` for an empty list.
///
/// Written out rather than printed as a debug list, because these appear in a
/// sentence somebody reads under time pressure.
fn listed(items: &[String]) -> String {
    match items {
        [] => "nothing".to_string(),
        [one] => one.clone(),
        [rest @ .., last] => format!("{} and {last}", rest.join(", ")),
    }
}

impl std::fmt::Display for BindingError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BindingError::Project(e) => write!(f, "{e}"),
            BindingError::Unbound { path } => write!(
                f,
                "{} does not bind a Cloudflare account. Add one, then this \
                 project can name its own workers and zones:\n  \
                 [identity.cloudflare]\n  account_id = \"…\"\n\
                 `apex cf status` prints the ids this credential can see",
                path.display()
            ),
            BindingError::BadId { path, key } => {
                // The shape depends on which key it is: a D1 database id is a
                // UUID and everything else here is 32 hex, so a message that
                // named only one of them would send half its readers looking
                // for the wrong thing.
                let want = key
                    .strip_prefix("cloudflare.")
                    .and_then(|rest| rest.split('.').next())
                    .and_then(|table| RESOURCES.iter().find(|(name, _, _)| name == &table))
                    .map(|(_, shape, _)| shape.describe())
                    .unwrap_or("32 hexadecimal characters");
                write!(
                    f,
                    "{} sets {key} to something that is not a Cloudflare id. \
                     One is {want}",
                    path.display()
                )
            }
            BindingError::BadName { path, table, named } => write!(
                f,
                "{} binds a resource called '{}' under [cloudflare.{table}], and \
                 that is not a name a request can carry. Use letters, digits, \
                 '_', '.' and '-'",
                path.display(),
                named.escape_debug()
            ),
            BindingError::NoAccount { path, account } => match account {
                Some(name) => write!(
                    f,
                    "{} names the account '{}' but not its id, and the API is \
                     addressed by id. Add `account_id` under \
                     [identity.cloudflare]; `apex cf status` prints it",
                    path.display(),
                    name.escape_debug()
                ),
                None => write!(
                    f,
                    "{} does not set `account_id` under [identity.cloudflare], \
                     so there is no account to act in. `apex cf status` prints \
                     the ids this credential can see",
                    path.display()
                ),
            },
            BindingError::NoWorker { path, named, bound } => write!(
                f,
                "this project does not bind a worker called '{}'. {} binds {}. \
                 A worker belongs to an environment:\n  \
                 [cloudflare.production]\n  worker = \"{}\"",
                named.escape_debug(),
                path.display(),
                listed(bound),
                named.escape_debug()
            ),
            BindingError::NoZone { path, named, bound } => match bound {
                Some(zone) => write!(
                    f,
                    "this project is bound to the zone {}, not to '{}'. Change \
                     `zone` under [cloudflare] in {} if that is wrong",
                    zone,
                    named.escape_debug(),
                    path.display()
                ),
                None => write!(
                    f,
                    "this project binds no zone, so '{}' is not one it may act \
                     on. Set `zone` under [cloudflare] in {}",
                    named.escape_debug(),
                    path.display()
                ),
            },
            BindingError::NoBucket { path, named, bound } => write!(
                f,
                "this project does not bind a bucket called '{}'. {} binds {}. \
                 Add it to `buckets` under [cloudflare] if it should be there",
                named.escape_debug(),
                path.display(),
                listed(bound)
            ),
            BindingError::NoRecord {
                path,
                named,
                zone,
                bound,
            } => {
                if bound.is_empty() {
                    write!(
                        f,
                        "'{}' is not a name in {zone}, which is the zone {} \
                         binds. A project may only act on records in its own \
                         zone",
                        named.escape_debug(),
                        path.display()
                    )
                } else {
                    write!(
                        f,
                        "this project does not bind a record called '{}'. {} \
                         narrows [cloudflare] records to {}. Add it there if it \
                         should be one",
                        named.escape_debug(),
                        path.display(),
                        listed(bound)
                    )
                }
            }
            BindingError::NoResource {
                path,
                table,
                kind,
                named,
                bound,
            } => write!(
                f,
                "this project does not bind a {kind} called '{}'. {} binds {} \
                 under [cloudflare.{table}]. A {kind} is bound by name and id:\n  \
                 [cloudflare.{table}]\n  {} = \"…\"",
                named.escape_debug(),
                path.display(),
                listed(bound),
                named.escape_debug()
            ),
            BindingError::ReservedSection { path, name } => write!(
                f,
                "{} has a [cloudflare.{name}] section with a worker in it, and \
                 '{name}' is the name of a resource table. Rename the \
                 environment: one section cannot be both",
                path.display()
            ),
            BindingError::NoZoneId { path, zone } => write!(
                f,
                "{} binds the zone {zone} but not its id, and a zone-scoped \
                 call is addressed by id. Add `zone_id` under [cloudflare]",
                path.display()
            ),
        }
    }
}

impl std::error::Error for BindingError {}

impl From<ProjectError> for BindingError {
    fn from(e: ProjectError) -> BindingError {
        BindingError::Project(e)
    }
}

/// A resolved account, and the label to call it by in a message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Account {
    pub id: String,
    pub label: Option<String>,
}

impl Account {
    /// How the account is named to a person: its own name where the project
    /// gave one, its id otherwise.
    pub fn named(&self) -> &str {
        self.label.as_deref().unwrap_or(&self.id)
    }
}

/// A worker this project binds, and the environment that binds it.
///
/// The environment travels with it because §13.8 makes `production` different
/// from `preview`, and P1-014 decides that from this field rather than by
/// parsing a name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Worker {
    pub account: Account,
    pub name: String,
    pub environment: String,
}

/// A zone this project binds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Zone {
    pub id: String,
    pub name: String,
}

/// A bucket this project binds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Bucket {
    pub account: Account,
    pub name: String,
}

/// `8-4-4-4-12` lower-case hex, which is what a D1 database id is.
///
/// Written out rather than pulled in as a dependency, and strict about case
/// for the same reason [`valid_id`] is: this goes into a URL path, and the set
/// of characters that cannot appear there is the point.
fn valid_uuid(id: &str) -> bool {
    let groups: Vec<&str> = id.split('-').collect();
    if groups.len() != 5 {
        return false;
    }
    for (group, want) in groups.iter().zip([8, 4, 4, 4, 12]) {
        if group.len() != want
            || !group.bytes().all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        {
            return false;
        }
    }
    true
}

/// Whether a string off the wire is a Secrets Store secret id.
///
/// Checked for the reason [`super::dns::is_record_id`] is: it is interpolated
/// into the URL of the request that CHANGES something, and unlike everything
/// else in a path here it came off the wire rather than out of the project's
/// own file.
pub fn valid_store_id(id: &str) -> bool {
    valid_id(id)
}

/// A Workers AI model name, as it appears in a URL path.
///
/// `@` then `/`-separated segments. Strict about the same things every other
/// shape here is strict about, and one more: no segment may be `.` or `..`,
/// because this is interpolated into a path and a model name is the one id in
/// this file that legitimately contains slashes.
fn valid_model(id: &str) -> bool {
    let Some(rest) = id.strip_prefix('@') else {
        return false;
    };
    if rest.is_empty() || rest.len() > 120 {
        return false;
    }
    let segments: Vec<&str> = rest.split('/').collect();
    // `@cf/author/model` is the documented shape; two segments is the fewest
    // that can name anything.
    if segments.len() < 2 {
        return false;
    }
    segments.iter().all(|segment| {
        !segment.is_empty()
            && *segment != "."
            && *segment != ".."
            && segment
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'_' | b'-'))
    })
}

pub(crate) fn valid_id(id: &str) -> bool {
    id.len() == ID_LEN && id.bytes().all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
}

/// Cloudflare's own pattern for an account-chosen id: `^[a-z0-9_]+(?:-[a-z0-9_]+)*$`.
///
/// Written out rather than pulled in as a regex, and strict for the reason the
/// other two are — this ends up in a URL path. The pattern's shape matters: a
/// leading, trailing or doubled `-` is refused, which a naive "letters, digits
/// and dashes" test would accept.
fn valid_slug(id: &str) -> bool {
    if id.is_empty() || id.len() > 64 {
        return false;
    }
    id.split('-').all(|group| {
        !group.is_empty()
            && group
                .bytes()
                .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
    })
}

impl Binding {
    /// Read `<project>/apex.toml` as the account the operation runs as.
    pub fn read(project: &Path, owner_uid: u32, owner_name: &str) -> Result<Binding, BindingError> {
        let config = ProjectConfig::read(project, owner_uid, owner_name)?;
        Binding::of(&config)
    }

    /// Pull §13.1's keys out of a parsed project file.
    pub fn of(config: &ProjectConfig) -> Result<Binding, BindingError> {
        let path = config.path().to_path_buf();
        let id = |key: &[&str]| -> Result<Option<String>, BindingError> {
            match config.string(key)? {
                None => Ok(None),
                Some(value) if valid_id(value) => Ok(Some(value.to_string())),
                Some(_) => Err(BindingError::BadId {
                    path: path.clone(),
                    key: key.join("."),
                }),
            }
        };

        let mut environments = BTreeMap::new();
        for name in config.sections(&["cloudflare"]) {
            // A resource table is not an environment. Without this an
            // environment could be called `kv`, and `[cloudflare.kv]` would
            // have to be both a list of namespaces and a worker binding —
            // which would read the key `worker` as a namespace called
            // "worker" and refuse the whole file for a bad id. Refused by
            // name instead, so the person is told what actually collided.
            if RESOURCES.iter().any(|(table, _, _)| *table == name) {
                if config.string(&["cloudflare", &name, "worker"])?.is_some() {
                    return Err(BindingError::ReservedSection {
                        path: path.clone(),
                        name: name.clone(),
                    });
                }
                continue;
            }
            if let Some(worker) = config.string(&["cloudflare", &name, "worker"])? {
                environments.insert(name, worker.to_string());
            }
        }

        let mut resources = BTreeMap::new();
        for (table, shape, kind) in RESOURCES {
            let mut bound = BTreeMap::new();
            for (name, id) in config.pairs(&["cloudflare", table])? {
                // A name the vocabulary could never carry is refused where it
                // is written rather than being silently unaddressable: a
                // namespace called `my cache` is not a `Syntax::Name`, so no
                // request could ever name it.
                if !operation::valid_name(&name) {
                    return Err(BindingError::BadName {
                        path: path.clone(),
                        table: table.to_string(),
                        named: name,
                    });
                }
                if !shape.accepts(&id) {
                    return Err(BindingError::BadId {
                        path: path.clone(),
                        key: format!("cloudflare.{table}.{name}"),
                    });
                }
                let _ = kind;
                bound.insert(name, id);
            }
            resources.insert(table.to_string(), bound);
        }

        Ok(Binding {
            account: config.string(&["identity", "cloudflare", "account"])?.map(str::to_string),
            account_id: id(&["identity", "cloudflare", "account_id"])?,
            zone: config.string(&["cloudflare", "zone"])?.map(str::to_string),
            zone_id: id(&["cloudflare", "zone_id"])?,
            buckets: config.strings(&["cloudflare", "buckets"])?,
            records: config.strings(&["cloudflare", "records"])?,
            resources,
            environments,
            path,
        })
    }

    /// Whether the file said anything about Cloudflare at all.
    ///
    /// Told apart from "bound, but not to that" because the fix is different:
    /// one is a file to write, the other is a line to change.
    pub fn is_empty(&self) -> bool {
        self.account.is_none()
            && self.account_id.is_none()
            && self.zone.is_none()
            && self.buckets.is_empty()
            && self.records.is_empty()
            && self.environments.is_empty()
            // Every table, or a project that binds only `[cloudflare.kv]` is
            // told to write a file it has already written.
            && self.resources.values().all(BTreeMap::is_empty)
    }

    /// The account every account-scoped call is addressed to.
    pub fn account(&self) -> Result<Account, BindingError> {
        if self.is_empty() {
            return Err(BindingError::Unbound {
                path: self.path.clone(),
            });
        }
        let Some(id) = self.account_id.clone() else {
            return Err(BindingError::NoAccount {
                path: self.path.clone(),
                account: self.account.clone(),
            });
        };
        Ok(Account {
            id,
            label: self.account.clone(),
        })
    }

    /// The workers this project binds, sorted, for a message.
    pub fn workers(&self) -> Vec<String> {
        let mut names: Vec<String> = self.environments.values().cloned().collect();
        names.sort();
        names.dedup();
        names
    }

    /// What a worker NAME means: an account, and the environment that binds it.
    ///
    /// A name no environment binds is refused. That is the whole of "an
    /// operation on a resource the project is not bound to is refused" for
    /// §13.3's Workers surface, and it is why the grant can be per-operation
    /// without also having to be per-worker.
    pub fn worker(&self, named: &str) -> Result<Worker, BindingError> {
        let account = self.account()?;
        // Sorted by environment name, so a worker bound to two environments
        // resolves the same way twice rather than by hash order.
        let found = self
            .environments
            .iter()
            .find(|(_, worker)| worker.as_str() == named);
        let Some((environment, name)) = found else {
            return Err(BindingError::NoWorker {
                path: self.path.clone(),
                named: named.to_string(),
                bound: self.workers(),
            });
        };
        Ok(Worker {
            account,
            name: name.clone(),
            environment: environment.clone(),
        })
    }

    /// What a zone NAME means. `example.com` resolves; anything else does not.
    pub fn zone(&self, named: &str) -> Result<Zone, BindingError> {
        let Some(zone) = self.zone.as_deref().filter(|z| *z == named) else {
            return Err(BindingError::NoZone {
                path: self.path.clone(),
                named: named.to_string(),
                bound: self.zone.clone(),
            });
        };
        let Some(id) = self.zone_id.clone() else {
            return Err(BindingError::NoZoneId {
                path: self.path.clone(),
                zone: zone.to_string(),
            });
        };
        Ok(Zone {
            id,
            name: zone.to_string(),
        })
    }

    /// What a name in one of the resource tables means: an account, and the id
    /// the API is addressed by.
    ///
    /// One resolver for D1, KV, Queues and Hyperdrive, because §13.1's answer
    /// is the same for all four — *the project writes the name down next to the
    /// id, or the request does not happen.* The four differ in what the id
    /// looks like and in nothing else, and that difference is handled where the
    /// file is read rather than here.
    pub fn resource(&self, table: &str, named: &str) -> Result<Resource, BindingError> {
        let account = self.account()?;
        let kind = RESOURCES
            .iter()
            .find(|(name, _, _)| *name == table)
            .map(|(_, _, kind)| *kind)
            .unwrap_or(table);
        let bound = self.resources.get(table);
        let Some(id) = bound.and_then(|t| t.get(named)) else {
            return Err(BindingError::NoResource {
                path: self.path.clone(),
                table: table.to_string(),
                kind: kind.to_string(),
                named: named.to_string(),
                bound: bound.map(|t| t.keys().cloned().collect()).unwrap_or_default(),
            });
        };
        Ok(Resource {
            account,
            name: named.to_string(),
            id: id.clone(),
        })
    }

    /// What a record NAME means: a name inside the bound zone that this
    /// project is allowed to touch.
    ///
    /// §13.9's "ordinary project grants may operate only on bound zones and
    /// records", in the two steps it actually has:
    ///
    /// * the name must be inside the bound zone, on a **label boundary** —
    ///   `notexample.com` is not in `example.com`, and a suffix test without
    ///   the dot would say it was;
    /// * if the project narrowed itself with `records`, the name must be one
    ///   of those. An entry may be written either way round — `www` or
    ///   `www.example.com` — because both are how people write them, and the
    ///   zone is right there to complete the short form.
    ///
    /// A project that lists no records gets its whole zone, which is the
    /// narrowing §13.9 asks for and no more. The elevated shapes are refused
    /// on top of this, by type, in [`super::dns::elevated`].
    pub fn record(&self, named: &str) -> Result<super::dns::Record, BindingError> {
        let Some(zone_name) = self.zone.clone() else {
            return Err(BindingError::NoZone {
                path: self.path.clone(),
                named: named.to_string(),
                bound: None,
            });
        };
        let zone = self.zone(&zone_name)?;
        if !super::dns::inside(&zone.name, named) {
            return Err(BindingError::NoRecord {
                path: self.path.clone(),
                named: named.to_string(),
                zone: zone.name.clone(),
                bound: Vec::new(),
            });
        }
        if !self.records.is_empty() {
            let allowed = self.records.iter().any(|bound| {
                bound == named || format!("{bound}.{}", zone.name) == named
            });
            if !allowed {
                return Err(BindingError::NoRecord {
                    path: self.path.clone(),
                    named: named.to_string(),
                    zone: zone.name.clone(),
                    bound: self.records.clone(),
                });
            }
        }
        Ok(super::dns::Record {
            zone,
            name: named.to_string(),
            kind: None,
        })
    }

    /// What a bucket NAME means: an account, and a bucket in it.
    ///
    /// §13.5's, and therefore P1-005's. It was written here ahead of any
    /// operation that calls it, because *what a Cloudflare name means* is one
    /// question and answering it in one module is the point of this file — a
    /// second resolver written next to R2's operations would be a second place
    /// for "the project did not bind that" to be decided differently. P1-005's
    /// three operations are what reach it now.
    ///
    /// A bucket is the one resource that can be named before it exists:
    /// `cloudflare.r2.bucket.create` makes the thing the project already
    /// declares. So this answers for a name in the file, not for a bucket in
    /// the account, and the difference is deliberate — the account is not
    /// something `bind` may ask about.
    pub fn bucket(&self, named: &str) -> Result<Bucket, BindingError> {
        let account = self.account()?;
        if !self.buckets.iter().any(|b| b == named) {
            return Err(BindingError::NoBucket {
                path: self.path.clone(),
                named: named.to_string(),
                bound: self.buckets.clone(),
            });
        }
        Ok(Bucket {
            account,
            name: named.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FULL: &str = r#"
[identity.cloudflare]
account = "example-account"
account_id = "0123456789abcdef0123456789abcdef"

[cloudflare]
zone = "example.com"
zone_id = "fedcba9876543210fedcba9876543210"
buckets = ["example-assets", "example-backups"]

[cloudflare.preview]
worker = "project-preview"

[cloudflare.production]
worker = "project"
"#;

    fn binding(text: &str) -> Binding {
        let config = ProjectConfig::parse(Path::new("/p/apex.toml"), text).expect("parses");
        Binding::of(&config).expect("binds")
    }

    #[test]
    fn section_thirteen_ones_own_example_binds() {
        // §13.1 verbatim, plus the two ids the REST API needs and §13.1 does
        // not mention. If this stops working the documented shape has drifted.
        let b = binding(FULL);
        assert_eq!(b.account().unwrap().id, "0123456789abcdef0123456789abcdef");
        assert_eq!(b.account().unwrap().named(), "example-account");
        assert_eq!(b.workers(), vec!["project", "project-preview"]);
        assert_eq!(b.zone("example.com").unwrap().name, "example.com");
        assert_eq!(b.bucket("example-assets").unwrap().name, "example-assets");
    }

    #[test]
    fn a_worker_resolves_to_an_account_and_the_environment_that_binds_it() {
        // The semantic claim: a NAME is not passed through, it is resolved
        // into a target, and the environment comes with it because §13.8
        // treats production differently.
        let b = binding(FULL);
        let production = b.worker("project").expect("bound");
        assert_eq!(production.environment, "production");
        assert_eq!(production.account.id, "0123456789abcdef0123456789abcdef");
        let preview = b.worker("project-preview").expect("bound");
        assert_eq!(preview.environment, "preview");
    }

    #[test]
    fn a_worker_this_project_does_not_bind_is_refused_and_the_message_says_what_is() {
        // "Refused with a reason a human can act on" — the fix is a line in a
        // file, so the message names the file and what is in it.
        let b = binding(FULL);
        let err = b.worker("somebody-elses-worker").unwrap_err();
        let text = err.to_string();
        assert!(text.contains("somebody-elses-worker"), "{text}");
        assert!(text.contains("/p/apex.toml"), "{text}");
        assert!(text.contains("project and project-preview"), "{text}");
        assert!(text.contains("[cloudflare.production]"), "{text}");
    }

    #[test]
    fn a_zone_that_is_not_this_project_s_zone_is_refused() {
        let b = binding(FULL);
        let err = b.zone("attacker.example").unwrap_err();
        let text = err.to_string();
        assert!(text.contains("example.com"), "{text}");
        assert!(text.contains("attacker.example"), "{text}");
        // ...and a project with no zone at all says that instead, because the
        // fix is to add a line rather than to change one.
        let none = binding("[identity.cloudflare]\naccount_id = \"0123456789abcdef0123456789abcdef\"\n");
        assert!(none.zone("example.com").unwrap_err().to_string().contains("binds no zone"));
    }

    #[test]
    fn a_zone_bound_by_name_but_not_by_id_says_which_key_is_missing() {
        let b = binding("[cloudflare]\nzone = \"example.com\"\n");
        let err = b.zone("example.com").unwrap_err();
        assert!(matches!(err, BindingError::NoZoneId { .. }));
        assert!(err.to_string().contains("zone_id"), "{err}");
    }

    #[test]
    fn a_project_that_binds_nothing_is_told_apart_from_one_bound_elsewhere() {
        // Two different fixes, so two different messages.
        let empty = binding("[something.else]\nkey = \"value\"\n");
        assert!(empty.is_empty());
        let err = empty.worker("project").unwrap_err();
        assert!(matches!(err, BindingError::Unbound { .. }), "{err:?}");
        assert!(err.to_string().contains("[identity.cloudflare]"), "{err}");

        let named = binding("[identity.cloudflare]\naccount = \"example-account\"\n");
        let err = named.worker("project").unwrap_err();
        assert!(matches!(err, BindingError::NoAccount { .. }), "{err:?}");
        assert!(err.to_string().contains("example-account"), "{err}");
        assert!(err.to_string().contains("account_id"), "{err}");
    }

    #[test]
    fn an_id_that_is_not_an_id_is_refused_at_read_time() {
        // The account id is interpolated into a URL path. A value that is not
        // {ID_LEN} hex characters is refused here rather than being sent.
        for evil in [
            "0123456789abcdef0123456789abcde",   // one short
            "0123456789abcdef0123456789abcdeff", // one long
            "0123456789ABCDEF0123456789ABCDEF",  // upper case
            "../../accounts/somebody-else000",
            "0123456789abcdef0123456789abcde/",
        ] {
            let text = format!("[identity.cloudflare]\naccount_id = \"{evil}\"\n");
            let config = ProjectConfig::parse(Path::new("/p/apex.toml"), &text).expect("parses");
            let err = Binding::of(&config).unwrap_err();
            assert!(
                matches!(err, BindingError::BadId { .. }),
                "'{evil}' was accepted as an id"
            );
        }
        // ...and the shape a real one has is accepted.
        assert!(binding(FULL).account().is_ok());
    }

    #[test]
    fn a_model_name_is_checked_as_strictly_as_every_other_id() {
        // A model name is the one id in this file that legitimately contains
        // slashes, and it is interpolated into the path of a call that spends
        // money. Every other shape here can rely on "no slashes" doing the
        // work; this one cannot, so it says what a segment may be instead.
        for evil in [
            "cf/meta/llama-3.1-8b-instruct",       // no '@' at all
            "@",                                   // nothing after it
            "@cf",                                 // one segment names nothing
            "@cf/../../accounts/somebody-else/ai", // the reason segments are checked
            "@cf/./llama",
            "@cf//llama",                          // an empty segment
            "@cf/meta/llama?per_page=1",           // a query, not a name
            "@cf/meta/llama#x",
            "@cf/meta/llama%2e%2e",
            "@cf/meta/llama instruct",             // a space
            "@cf/meta/llama\n",
        ] {
            let text = format!(
                "[identity.cloudflare]\naccount_id = \"0123456789abcdef0123456789abcdef\"\n\
                 [cloudflare.models]\nfast = \"{}\"\n",
                evil.escape_debug()
            );
            let config = ProjectConfig::parse(Path::new("/p/apex.toml"), &text).expect("parses");
            let err = Binding::of(&config).unwrap_err();
            assert!(
                matches!(err, BindingError::BadId { .. }),
                "'{}' was accepted as a model name",
                evil.escape_debug()
            );
        }

        // ...and the documented shape is accepted, from Cloudflare's own
        // Workers AI REST example.
        let good = "[identity.cloudflare]\naccount_id = \"0123456789abcdef0123456789abcdef\"\n\
                    [cloudflare.models]\nfast = \"@cf/meta/llama-3.1-8b-instruct\"\n\
                    [cloudflare.gateways]\nmain = \"apex-gateway\"\n";
        let b = binding(good);
        assert_eq!(b.resource("models", "fast").expect("bound").id, "@cf/meta/llama-3.1-8b-instruct");
        assert_eq!(b.resource("gateways", "main").expect("bound").id, "apex-gateway");

        // A gateway id is a slug, and a slug that is really a path is not one.
        for evil in ["../other", "Apex-Gateway", "apex gateway", "apex/gateway"] {
            let text = format!(
                "[identity.cloudflare]\naccount_id = \"0123456789abcdef0123456789abcdef\"\n\
                 [cloudflare.gateways]\nmain = \"{}\"\n",
                evil.escape_debug()
            );
            let config = ProjectConfig::parse(Path::new("/p/apex.toml"), &text).expect("parses");
            assert!(
                matches!(Binding::of(&config).unwrap_err(), BindingError::BadId { .. }),
                "'{}' was accepted as a gateway id",
                evil.escape_debug()
            );
        }
    }

    #[test]
    fn an_environment_with_no_worker_is_not_an_environment() {
        // A `[cloudflare.staging]` that sets something else must not make
        // `staging` resolve to an empty worker name.
        let b = binding(
            "[identity.cloudflare]\naccount_id = \"0123456789abcdef0123456789abcdef\"\n\
             [cloudflare.staging]\nnote = \"not a worker\"\n",
        );
        assert!(b.environments.is_empty());
        assert!(b.worker("").is_err());
    }

    #[test]
    fn a_bucket_this_project_does_not_bind_is_refused() {
        let b = binding(FULL);
        assert!(b.bucket("example-assets").is_ok());
        let err = b.bucket("somebody-elses-bucket").unwrap_err();
        assert!(err.to_string().contains("example-assets and example-backups"), "{err}");
    }

    #[test]
    fn one_thing_bound_does_not_bind_the_others() {
        // The point of a semantic binding: binding a worker does not bind a
        // zone, and binding a zone does not bind a bucket. A provider that
        // treated "the project is a Cloudflare project" as the check would
        // pass all three.
        let b = binding(
            "[identity.cloudflare]\naccount_id = \"0123456789abcdef0123456789abcdef\"\n\
             [cloudflare.production]\nworker = \"project\"\n",
        );
        assert!(b.worker("project").is_ok());
        assert!(b.zone("example.com").is_err());
        assert!(b.bucket("project").is_err());
    }

    #[test]
    fn a_list_of_names_reads_as_a_sentence() {
        assert_eq!(listed(&[]), "nothing");
        assert_eq!(listed(&["a".into()]), "a");
        assert_eq!(listed(&["a".into(), "b".into()]), "a and b");
        assert_eq!(listed(&["a".into(), "b".into(), "c".into()]), "a, b and c");
    }
}
