package com.apexos.remote.core

import java.io.ByteArrayOutputStream

/**
 * The encrypted channel, and the two handshakes that open one.
 *
 * A port of `apexd/apex-remote-core/src/noise.rs`, which uses `snow`. Nothing
 * equivalent to `snow` exists for Kotlin that is worth trusting — the one
 * Java implementation of Noise is unmaintained and is not on Maven Central —
 * so the two patterns this protocol uses are written out here over
 * BouncyCastle's primitives. That is a real cost, and it is paid for in one
 * way only: the tests beside this replay **byte vectors generated by `snow`
 * itself**, with fixed statics and fixed ephemerals, and assert that this
 * implementation produces the same bytes. An implementation that merely talks
 * to itself would pass every test in this file and interoperate with nothing.
 *
 * ## Two patterns, for two different situations
 *
 * **`Noise_NK` for pairing.** The device has just scanned a QR code, so it
 * knows the desktop's static public key and the desktop knows nothing about
 * the device. The device sends its own static key and the one-time pairing
 * token *inside* the encrypted handshake payload.
 *
 * **`Noise_IK` afterwards.** Both statics are known, and IK transmits the
 * initiator's static encrypted to the responder's — so a relay operator
 * carrying the bytes never learns which device is connecting.
 *
 * `XX` is not used anywhere: it would let a device connect without knowing the
 * desktop's key in advance, and that is the property that makes a man in the
 * middle possible.
 */
object Noise {
    /**
     * The cipher suite, for both patterns.
     *
     * ChaCha20-Poly1305 rather than AES-GCM because a phone and a laptop do
     * not reliably both have AES hardware, and ChaCha is constant-time in
     * software where AES is not. BLAKE2s rather than SHA-256 for the same
     * reason on the same devices.
     */
    const val PAIRING_PATTERN = "Noise_NK_25519_ChaChaPoly_BLAKE2s"
    const val SESSION_PATTERN = "Noise_IK_25519_ChaChaPoly_BLAKE2s"

    /** The largest Noise message, including its authentication tag. */
    const val MAX_MESSAGE = 65535

    /**
     * Everything both patterns agree on before a byte is sent: the literal
     * bytes `apex-remote/<version>`.
     *
     * The version is in here rather than in a frame, because a frame is only
     * readable after the handshake and a version mismatch has to be catchable
     * before that. Noise binds the prologue into the handshake hash, so two
     * ends that disagree do not complete.
     */
    fun prologue(version: Int): ByteArray = "apex-remote/$version".toByteArray(Charsets.US_ASCII)

    /** The device's side of pairing: it knows the desktop's key from the QR. */
    fun pairingInitiator(
        desktopPublic: ByteArray,
        version: Int,
        ephemerals: EphemeralSource = EphemeralSource.Secure,
    ): Handshake = Handshake(
        initiator = true,
        pattern = NK,
        protocolName = PAIRING_PATTERN,
        prologue = prologue(version),
        localStatic = null,
        remoteStaticIn = desktopPublic.copyOf(),
        preMessageRemoteStatic = true,
        ephemerals = ephemerals,
    )

    /** The desktop's side of pairing. Present so a test can be both ends. */
    fun pairingResponder(
        localStatic: StaticKey,
        version: Int,
        ephemerals: EphemeralSource = EphemeralSource.Secure,
    ): Handshake = Handshake(
        initiator = false,
        pattern = NK,
        protocolName = PAIRING_PATTERN,
        prologue = prologue(version),
        localStatic = localStatic,
        remoteStaticIn = null,
        preMessageRemoteStatic = true,
        ephemerals = ephemerals,
    )

    /** A paired device opening a session. */
    fun sessionInitiator(
        localStatic: StaticKey,
        desktopPublic: ByteArray,
        version: Int,
        ephemerals: EphemeralSource = EphemeralSource.Secure,
    ): Handshake = Handshake(
        initiator = true,
        pattern = IK,
        protocolName = SESSION_PATTERN,
        prologue = prologue(version),
        localStatic = localStatic,
        remoteStaticIn = desktopPublic.copyOf(),
        preMessageRemoteStatic = true,
        ephemerals = ephemerals,
    )

    /** The desktop accepting a session from a device it has not yet identified. */
    fun sessionResponder(
        localStatic: StaticKey,
        version: Int,
        ephemerals: EphemeralSource = EphemeralSource.Secure,
    ): Handshake = Handshake(
        initiator = false,
        pattern = IK,
        protocolName = SESSION_PATTERN,
        prologue = prologue(version),
        localStatic = localStatic,
        remoteStaticIn = null,
        preMessageRemoteStatic = true,
        ephemerals = ephemerals,
    )

    internal enum class Token { E, S, EE, ES, SE, SS }

    /** `-> e, es` then `<- e, ee`. The responder's static is a pre-message. */
    internal val NK: List<List<Token>> = listOf(
        listOf(Token.E, Token.ES),
        listOf(Token.E, Token.EE),
    )

    /** `-> e, es, s, ss` then `<- e, ee, se`. */
    internal val IK: List<List<Token>> = listOf(
        listOf(Token.E, Token.ES, Token.S, Token.SS),
        listOf(Token.E, Token.EE, Token.SE),
    )
}

/** Why a channel could not be opened or used. */
sealed class NoiseError {
    /**
     * The primitives refused something: a bad key, a failed decryption, a
     * handshake message out of order.
     *
     * Deliberately one variant rather than a taxonomy. Every one of them means
     * the same thing to a caller — this peer is not who it claims to be, or
     * the bytes have been tampered with — and a caller that branched on which
     * would be making a distinction the security model does not have.
     */
    data class Crypto(val why: String) : NoiseError()

    /** A message larger than Noise can carry. */
    data class TooLong(val length: Int) : NoiseError()

    /** A handshake payload that is not the shape it must be. */
    data class Malformed(val why: String) : NoiseError()

    val message: String
        get() = when (this) {
            is Crypto -> why
            is TooLong -> "a message of $length bytes exceeds ${Noise.MAX_MESSAGE}"
            is Malformed -> why
        }
}

class NoiseException(val error: NoiseError) : Exception(error.message)

/** An X25519 keypair whose secret half is in this process's memory. */
class KeyPair(val secret: ByteArray, val publicKey: ByteArray) {
    // No `toString` naming the secret, and no `data class`: a generated
    // `toString` would print the private key into any log line that formatted
    // this object, which on Android means into a crash report.
    override fun toString(): String = "KeyPair(public=${Base64Url.encode(publicKey)})"
}

/**
 * Where a handshake's ephemeral keys come from.
 *
 * An interface and not a call to `SecureRandom` inline, for exactly one
 * reason: cross-implementation test vectors are only reproducible if both
 * sides can be told which ephemeral to use. `snow` exposes the same seam as
 * `fixed_ephemeral_key_for_testing_only`.
 */
fun interface EphemeralSource {
    fun generate(): KeyPair

    companion object {
        val Secure: EphemeralSource = EphemeralSource {
            val secret = Crypto.generateSecret()
            KeyPair(secret, Crypto.publicFromSecret(secret))
        }

        /** Test only. Named so that a use in shipped code is obvious in review. */
        fun fixedForTestingOnly(secret: ByteArray): EphemeralSource = EphemeralSource {
            KeyPair(secret.copyOf(), Crypto.publicFromSecret(secret))
        }
    }
}

/** One side of a handshake in progress. */
class Handshake internal constructor(
    private val initiator: Boolean,
    private val pattern: List<List<Noise.Token>>,
    protocolName: String,
    prologue: ByteArray,
    private val localStatic: StaticKey?,
    remoteStaticIn: ByteArray?,
    preMessageRemoteStatic: Boolean,
    private val ephemerals: EphemeralSource,
) {
    private val sym = SymmetricState(protocolName)
    private var e: KeyPair? = null
    private var re: ByteArray? = null
    private var rs: ByteArray? = remoteStaticIn
    private var index = 0
    private var split: Pair<CipherState, CipherState>? = null

    init {
        sym.mixHash(prologue)
        if (preMessageRemoteStatic) {
            // The responder's static is the one pre-message both patterns
            // carry, and both ends mix it: the initiator the key it pinned
            // from the QR, the responder its own. A man in the middle that
            // substituted its key would be mixing a different value and the
            // handshake would not complete.
            val known = if (initiator) rs else localStatic?.publicKey
            requireNotNull(known) { "the responder's static key is a pre-message and must be known" }
            sym.mixHash(known)
        }
    }

    val isHandshakeFinished: Boolean get() = index >= pattern.size

    /**
     * The peer's static public key, once the pattern has transmitted one.
     *
     * `null` on a `NK` responder, where the initiator has no static at all —
     * the device's key is in the *payload* there, because pairing is the
     * moment it becomes known and there is nothing yet to authenticate it
     * against.
     */
    val remoteStatic: ByteArray? get() = rs?.copyOf()

    /** Write the next handshake message, carrying [payload]. */
    fun write(payload: ByteArray): ByteArray {
        if (isHandshakeFinished) fail("the handshake is finished and has no further message")
        if ((index % 2 == 0) != initiator) fail("it is the other end's turn to send")
        val out = ByteArrayOutputStream()
        for (token in pattern[index]) {
            when (token) {
                Noise.Token.E -> {
                    val kp = ephemerals.generate()
                    e = kp
                    out.write(kp.publicKey)
                    sym.mixHash(kp.publicKey)
                }
                Noise.Token.S -> {
                    val s = localStatic ?: fail("this pattern sends a static key and none was given")
                    out.write(sym.encryptAndHash(s.publicKey))
                }
                else -> mix(token)
            }
        }
        out.write(sym.encryptAndHash(payload))
        advance()
        return out.toByteArray()
    }

    /** Read the next handshake message, returning its payload. */
    fun read(message: ByteArray): ByteArray {
        if (message.size > Noise.MAX_MESSAGE) throw NoiseException(NoiseError.TooLong(message.size))
        if (isHandshakeFinished) fail("the handshake is finished and expects no further message")
        if ((index % 2 == 0) == initiator) fail("it is this end's turn to send, not to read")
        var off = 0
        for (token in pattern[index]) {
            when (token) {
                Noise.Token.E -> {
                    val end = need(off, Crypto.DHLEN, message.size, "an ephemeral public key")
                    val key = message.copyOfRange(off, end)
                    re = key
                    sym.mixHash(key)
                    off = end
                }
                Noise.Token.S -> {
                    val width = Crypto.DHLEN + if (sym.hasKey) Crypto.TAGLEN else 0
                    val end = need(off, width, message.size, "a static public key")
                    rs = sym.decryptAndHash(message.copyOfRange(off, end))
                    off = end
                }
                else -> mix(token)
            }
        }
        val payload = sym.decryptAndHash(message.copyOfRange(off, message.size))
        advance()
        return payload
    }

    /** Turn a finished handshake into a transport channel. */
    fun intoTransport(): NoiseChannel {
        val s = split ?: fail("the handshake has not finished")
        // The initiator's first key is its sending key and the responder's
        // first key is its receiving one. Getting this backwards produces two
        // ends that handshake perfectly and then cannot read each other, which
        // is the single most confusing failure this protocol has.
        return if (initiator) NoiseChannel(s.first, s.second) else NoiseChannel(s.second, s.first)
    }

    private fun mix(token: Noise.Token) {
        val ephemeral = { e ?: fail("no local ephemeral yet") }
        val theirE = { re ?: fail("no remote ephemeral yet") }
        val theirS = { rs ?: fail("no remote static yet") }
        val mine = { localStatic ?: fail("this pattern needs a local static key") }
        val ikm = when (token) {
            Noise.Token.EE -> Crypto.x25519(ephemeral().secret, theirE())
            // Role-based and not direction-based, exactly as the Noise
            // specification writes it: `es` is DH(e, rs) for the initiator and
            // DH(s, re) for the responder, whichever of them is sending.
            Noise.Token.ES -> if (initiator) {
                Crypto.x25519(ephemeral().secret, theirS())
            } else {
                mine().agree(theirE())
            }
            Noise.Token.SE -> if (initiator) {
                mine().agree(theirE())
            } else {
                Crypto.x25519(ephemeral().secret, theirS())
            }
            Noise.Token.SS -> mine().agree(theirS())
            Noise.Token.E, Noise.Token.S -> fail("$token is not a key-mixing token")
        }
        sym.mixKey(ikm)
    }

    private fun advance() {
        index++
        if (isHandshakeFinished) split = sym.split()
    }

    private fun need(off: Int, width: Int, size: Int, what: String): Int {
        if (off + width > size) {
            throw NoiseException(
                NoiseError.Malformed("the handshake message is too short to contain $what"),
            )
        }
        return off + width
    }

    private fun fail(why: String): Nothing = throw NoiseException(NoiseError.Crypto(why))
}

/**
 * An encrypted, authenticated, ordered channel.
 *
 * One channel per connection, carrying every multiplexed [Frame]. The nonce is
 * the message counter and neither side chooses it, so a replayed or reordered
 * message does not decrypt: that is the property the whole multiplexing layer
 * above rests on, because a frame arriving twice would be a keystroke arriving
 * twice.
 */
class NoiseChannel internal constructor(
    private val sending: CipherState,
    private val receiving: CipherState,
) {
    /** Encrypt one plaintext message. */
    fun seal(plaintext: ByteArray): ByteArray {
        if (plaintext.size + Crypto.TAGLEN > Noise.MAX_MESSAGE) {
            throw NoiseException(NoiseError.TooLong(plaintext.size))
        }
        return sending.encryptWithAd(EMPTY, plaintext)
    }

    /** Decrypt one message, or fail. */
    fun open(ciphertext: ByteArray): ByteArray {
        if (ciphertext.size > Noise.MAX_MESSAGE) {
            throw NoiseException(NoiseError.TooLong(ciphertext.size))
        }
        return receiving.decryptWithAd(EMPTY, ciphertext)
    }

    private companion object {
        val EMPTY = ByteArray(0)
    }
}

/**
 * Noise's `CipherState`: a key and a counter.
 *
 * The counter is this end's alone and is never transmitted, which is what
 * makes a replay undecryptable rather than merely detectable.
 */
internal class CipherState(private val k: ByteArray?) {
    private var n: Long = 0

    val hasKey: Boolean get() = k != null

    fun encryptWithAd(ad: ByteArray, plaintext: ByteArray): ByteArray {
        val key = k ?: return plaintext
        val out = try {
            Crypto.encrypt(key, Crypto.nonce(n), ad, plaintext)
        } catch (e: RuntimeException) {
            throw NoiseException(NoiseError.Crypto(e.message ?: e.javaClass.simpleName))
        }
        n++
        return out
    }

    fun decryptWithAd(ad: ByteArray, ciphertext: ByteArray): ByteArray {
        val key = k ?: return ciphertext
        // The counter advances only on a SUCCESSFUL decrypt. That is what
        // stops an attacker making the far end skip a message by injecting a
        // later one: the refused message leaves the channel exactly where it
        // was, and the message that was really next still opens.
        val out = try {
            Crypto.decrypt(key, Crypto.nonce(n), ad, ciphertext)
        } catch (e: org.bouncycastle.crypto.InvalidCipherTextException) {
            throw NoiseException(NoiseError.Crypto("the message did not authenticate"))
        } catch (e: RuntimeException) {
            throw NoiseException(NoiseError.Crypto(e.message ?: e.javaClass.simpleName))
        }
        n++
        return out
    }
}

/** Noise's `SymmetricState`: the chaining key, the handshake hash and a cipher. */
internal class SymmetricState(protocolName: String) {
    private var ck: ByteArray
    private var h: ByteArray
    private var cipher = CipherState(null)

    init {
        val name = protocolName.toByteArray(Charsets.US_ASCII)
        // Both pattern names are 33 bytes and therefore hashed. The padding
        // branch is kept because it is what the specification says and a
        // shorter suite name would otherwise silently take the wrong path.
        h = if (name.size <= Crypto.HASHLEN) name.copyOf(Crypto.HASHLEN) else Crypto.blake2s(name)
        ck = h.copyOf()
    }

    val hasKey: Boolean get() = cipher.hasKey

    fun mixHash(data: ByteArray) {
        h = Crypto.blake2s(h, data)
    }

    fun mixKey(ikm: ByteArray) {
        val (newCk, tempK) = Crypto.hkdf2(ck, ikm)
        ck = newCk
        cipher = CipherState(tempK)
    }

    fun encryptAndHash(plaintext: ByteArray): ByteArray {
        val ct = cipher.encryptWithAd(h, plaintext)
        mixHash(ct)
        return ct
    }

    fun decryptAndHash(ciphertext: ByteArray): ByteArray {
        val pt = cipher.decryptWithAd(h, ciphertext)
        mixHash(ciphertext)
        return pt
    }

    fun split(): Pair<CipherState, CipherState> {
        val (k1, k2) = Crypto.hkdf2(ck, ByteArray(0))
        return CipherState(k1) to CipherState(k2)
    }
}
