package com.apexos.remote.core.agent

import com.apexos.remote.core.Base64Url
import com.apexos.remote.core.PairedMachine
import com.apexos.remote.core.PushRegistration
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * The push envelope, against the bytes the desktop actually seals (P1-058).
 *
 * ## Why the vectors are the whole point
 *
 * This phone cannot use the `chacha20poly1305` crate, so [Push] derives its
 * AEAD key and opens its envelopes over BouncyCastle's primitives — a second
 * implementation of a format whose only other implementation is in Rust. A
 * suite that sealed an envelope here and opened it here would agree with
 * itself and with nothing else, and every mistake that matters produces
 * exactly that: HKDF with the wrong salt or the wrong counter byte, the
 * associated data left out, the fields packed little-endian, `started` read as
 * milliseconds, the kind and adapter bytes swapped.
 *
 * The consequence of any of them on a real phone is that no notification ever
 * arrives and nothing anywhere says why.
 *
 * So `push-vectors.json` is generated by `apex-remote-core`'s own sealing
 * code, committed, and asserted in BOTH suites: a Rust test fails if the
 * committed file stops matching what the desktop produces, and this one fails
 * if Kotlin cannot read it.
 */
class PushVectorsTest {
    private val vectors: JsonObject = run {
        val stream = javaClass.classLoader.getResourceAsStream("push-vectors.json")
            ?: error(
                "push-vectors.json is missing from the test resources. Regenerate it with " +
                    "`cargo test -p apex-remote-core -- --ignored write_the_android_push_vectors`",
            )
        Json.parseToJsonElement(stream.bufferedReader().readText()).jsonObject
    }

    private fun hex(text: String): ByteArray =
        ByteArray(text.length / 2) { text.substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    private val key: ByteArray get() = hex(vectors["key_hex"]!!.jsonPrimitive.content)

    @Test
    fun `the derived aead key is the one the desktop derives`() {
        // If this is wrong nothing below can pass, and the reason would be
        // buried in a tag mismatch. Asserted on its own so the failure names
        // HKDF rather than "the envelope did not open".
        assertEquals(
            vectors["aead_key_hex"]!!.jsonPrimitive.content,
            Push.aeadKey(key).joinToString("") { "%02x".format(it) },
            "HKDF-SHA256 over the registration key does not agree with the desktop's",
        )
    }

    @Test
    fun `hmac sha256 matches RFC 4231`() {
        // The construction is hand-written on both sides, so it is checked
        // against a published vector rather than against the other side.
        assertEquals(
            "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7",
            Push.hmacSha256(ByteArray(20) { 0x0b }, "Hi There".toByteArray())
                .joinToString("") { "%02x".format(it) },
        )
        assertEquals(
            "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843",
            Push.hmacSha256("Jefe".toByteArray(), "what do ya want for nothing?".toByteArray())
                .joinToString("") { "%02x".format(it) },
        )
        // Case 6: a key longer than the 64-byte block, which is the branch
        // that hashes it first and the one an implementation forgets.
        assertEquals(
            "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54",
            Push.hmacSha256(
                ByteArray(131) { 0xaa.toByte() },
                "Test Using Larger Than Block-Size Key - Hash Key First".toByteArray(),
            ).joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `every envelope the desktop seals opens here with the fields it sealed`() {
        val cases = vectors["cases"]!!.jsonArray
        assertTrue(cases.size >= 8, "the vectors cover only ${cases.size} kinds")
        for (case in cases) {
            val o = case.jsonObject
            val envelope = hex(o["envelope_hex"]!!.jsonPrimitive.content)
            assertEquals(
                Push.ENVELOPE_LEN,
                envelope.size,
                "the desktop sealed ${envelope.size} bytes and this build expects ${Push.ENVELOPE_LEN}",
            )
            val body = Push.open(key, envelope)
                ?: error("the envelope for kind ${o["kind"]} did not open")
            assertEquals(Push.kindOf(o["kind"]!!.jsonPrimitive.content.toInt()), body.kind)
            assertEquals(Push.adapterOf(o["adapter"]!!.jsonPrimitive.content.toInt()), body.agent)
            assertEquals(o["session"]!!.jsonPrimitive.content.toInt(), body.session)
            // Unix SECONDS, and the assertion is against the number the
            // desktop put in rather than against a rounded comparison: a
            // millisecond mix-up passes any "roughly now" check and fails
            // every session-identity check months later.
            assertEquals(o["started"]!!.jsonPrimitive.content.toLong(), body.started)
            assertEquals(o["seq"]!!.jsonPrimitive.content.toLong(), body.seq)
        }
    }

    @Test
    fun `the vocabulary is the same on both sides and no code is unmapped`() {
        val codes = vectors["cases"]!!.jsonArray
            .map { it.jsonObject["kind"]!!.jsonPrimitive.content.toInt() }
            .toSet()
        // Every kind the desktop can send is one this build renders. The
        // vectors walk `Kind::ALL`, so a kind added in Rust and not here fails
        // here rather than on somebody's phone.
        assertEquals(
            Alert.Kind.entries.map { Push.codeOf(it) }.toSet(),
            codes,
            "the desktop and this app disagree about the notification vocabulary",
        )
        // And the codes are stable: they are the wire, so renumbering one
        // would make an older phone render the wrong sentence.
        assertEquals(1, Push.codeOf(Alert.Kind.WAITING))
        assertEquals(8, Push.codeOf(Alert.Kind.DEPLOY_FAILED))
        for (code in codes) assertNotEquals(null, Push.kindOf(code))
        assertNull(Push.kindOf(0))
        assertNull(Push.kindOf(99))
    }

    @Test
    fun `an envelope from another machine or a tampered one does not open`() {
        val envelope = hex(
            vectors["cases"]!!.jsonArray[0].jsonObject["envelope_hex"]!!.jsonPrimitive.content,
        )
        assertNull(Push.open(ByteArray(Push.KEY_LEN) { 0x5a }, envelope), "it opened under a stranger's key")
        for (i in envelope.indices) {
            val bad = envelope.copyOf()
            bad[i] = (bad[i].toInt() xor 1).toByte()
            assertNull(Push.open(key, bad), "flipping byte $i left an envelope that still opened")
        }
        // Short, long, and empty are all "not an envelope" rather than crashes
        // — this runs in a BroadcastReceiver, where a throw is a process death
        // the user sees as the app crashing when a notification arrives.
        assertNull(Push.open(key, ByteArray(0)))
        assertNull(Push.open(key, envelope.copyOf(envelope.size - 1)))
        assertNull(Push.open(key, envelope + byteArrayOf(0)))
    }

    @Test
    fun `a kind this build has not been taught is dropped rather than renamed`() {
        // The envelope is authentic; only the kind byte is one from a newer
        // machine. Rendering it with a known kind's words would be a
        // notification that lies about what happened on the computer.
        val o = vectors["cases"]!!.jsonArray[0].jsonObject
        val plain = hex(o["plaintext_hex"]!!.jsonPrimitive.content)
        plain[0] = 99
        assertNull(Push.Body.unpack(plain))
        assertNull(Push.Body.unpack(ByteArray(Push.BODY_LEN - 1)))
    }

    @Test
    fun `nothing in the vectors is a word from the computer`() {
        // Criterion 2 read off the committed bytes themselves. These are the
        // real envelopes the desktop produces, and there is no printable
        // vocabulary in them at all, because the body is five integers.
        for (case in vectors["cases"]!!.jsonArray) {
            val envelope = hex(case.jsonObject["envelope_hex"]!!.jsonPrimitive.content)
            val text = String(envelope, Charsets.ISO_8859_1).lowercase()
            for (word in listOf("claude", "codex", "waiting", "session", "apex", "http", "/home")) {
                assertFalse(text.contains(word), "an envelope contained $word")
            }
        }
        assertEquals(22, vectors["body_len"]!!.jsonPrimitive.content.toInt())
        assertEquals(51, vectors["envelope_len"]!!.jsonPrimitive.content.toInt())
    }
}

/** The rules around the envelope, which need no vectors. */
class PushRulesTest {
    @Test
    fun `a push key is thirty two fresh bytes and two are never the same`() {
        val a = Push.newKey()
        val b = Push.newKey()
        assertEquals(Push.KEY_LEN, a.size)
        assertFalse(a.contentEquals(b), "two registration keys were identical")
        // The derived key must not be the key that was handed over: a
        // registration key reused for anything else would otherwise be the
        // same bytes.
        assertFalse(Push.aeadKey(a).contentEquals(a))
        assertTrue(Push.aeadKey(a).contentEquals(Push.aeadKey(a)))
    }

    @Test
    fun `a replayed delivery is dropped and a new one is not`() {
        // A distributor MAY retry a message whose acknowledgement it did not
        // see, and the acknowledgement can be lost, so the same bytes really
        // do arrive twice.
        val r = Push.Replay()
        assertTrue(r.accept(1))
        assertFalse(r.accept(1), "the same sequence was accepted twice")
        assertTrue(r.accept(2))
        assertFalse(r.accept(2))
        // Out of order: a distributor gives no ordering guarantee, and an
        // older envelope arriving after a newer one describes a moment that
        // has already been superseded.
        assertFalse(r.accept(1))
        assertTrue(r.accept(9))
        assertEquals(9, r.highest)
        // Restored from storage, so a process restart does not accept a replay
        // of everything the phone has already shown.
        val fresh = Push.Replay()
        fresh.restore(9)
        assertFalse(fresh.accept(9))
        assertTrue(fresh.accept(10))
    }

    @Test
    fun `a pushed alert and a polled alert for one moment are one notification`() {
        // P1-058's fourth criterion, at the seam that actually decides it.
        // The poll loop builds an Alert from a session record; the receiver
        // builds one from an envelope. If the two produce different ids, a
        // phone with a distributor installed shows every moment twice.
        val fromPoll = Alert("machine-1", 7, Alert.Kind.WAITING, "claude", 111)
        val body = Push.Body(Alert.Kind.WAITING, "claude", 7, 1_726_000_000, 4)
        val fromPush = Alert("machine-1", body.session, body.kind, body.agent, 222)
        assertEquals(
            NotificationContent.idFor(fromPoll.key),
            NotificationContent.idFor(fromPush.key),
            "a pushed and a polled alert for one moment would stack in the shade",
        )
        assertEquals(
            NotificationContent.of(fromPoll, "laptop").id,
            NotificationContent.of(fromPush, "laptop").id,
        )
        // And two different moments still get two notifications.
        val other = Alert("machine-1", 8, Alert.Kind.WAITING, "claude", 111)
        assertNotEquals(
            NotificationContent.idFor(fromPoll.key),
            NotificationContent.idFor(other.key),
        )
        val otherMachine = Alert("machine-2", 7, Alert.Kind.WAITING, "claude", 111)
        assertNotEquals(
            NotificationContent.idFor(fromPoll.key),
            NotificationContent.idFor(otherMachine.key),
        )
    }

    @Test
    fun `a deployment alert renders without naming anything on the computer`() {
        for (kind in listOf(Alert.Kind.DEPLOYED, Alert.Kind.DEPLOY_FAILED)) {
            val content = NotificationContent.of(Alert("m", 3, kind, "claude", 0), "laptop")
            assertTrue(content.title.isNotEmpty())
            assertTrue(content.text.isNotEmpty())
            // The same minimisation rule as every other kind: fixed strings, a
            // machine name and an adapter name, and nothing else.
            for (banned in listOf("/", "http", "$", "`")) {
                assertFalse(content.text.contains(banned), "${kind.name}: ${content.text}")
            }
        }
    }

    @Test
    fun `an adapter the desktop did not recognise renders as Agent`() {
        // The allowlist is enforced on the desktop, so what arrives is a code.
        // Code 0 is "an adapter this build has not been taught", and it must
        // not render as an empty name or as a number.
        assertEquals("", Push.adapterOf(0))
        assertEquals("Agent", AgentNames.of(Push.adapterOf(0)))
        assertEquals("Claude", AgentNames.of(Push.adapterOf(1)))
    }
}

/** The broadcast protocol, by the specification's own names. */
class UnifiedPushTest {
    @Test
    fun `the action and extra names are the specification's`() {
        // AND_3.0.0. Written out because a wrong name here fails SILENTLY —
        // the distributor simply never delivers and nothing logs anything.
        assertEquals("org.unifiedpush.android.distributor.REGISTER", UnifiedPush.ACTION_REGISTER)
        assertEquals("org.unifiedpush.android.distributor.UNREGISTER", UnifiedPush.ACTION_UNREGISTER)
        assertEquals("org.unifiedpush.android.distributor.MESSAGE_ACK", UnifiedPush.ACTION_MESSAGE_ACK)
        assertEquals("org.unifiedpush.android.connector.NEW_ENDPOINT", UnifiedPush.ACTION_NEW_ENDPOINT)
        assertEquals("org.unifiedpush.android.connector.MESSAGE", UnifiedPush.ACTION_MESSAGE)
        assertEquals(
            "org.unifiedpush.android.connector.REGISTRATION_FAILED",
            UnifiedPush.ACTION_REGISTRATION_FAILED,
        )
        assertEquals("org.unifiedpush.android.connector.UNREGISTERED", UnifiedPush.ACTION_UNREGISTERED)
        assertEquals("token", UnifiedPush.EXTRA_TOKEN)
        assertEquals("endpoint", UnifiedPush.EXTRA_ENDPOINT)
        assertEquals("bytesMessage", UnifiedPush.EXTRA_BYTES_MESSAGE)
        assertEquals("id", UnifiedPush.EXTRA_MESSAGE_ID)
        assertEquals("application", UnifiedPush.EXTRA_APPLICATION)
        assertEquals("reason", UnifiedPush.EXTRA_REASON)
        assertEquals("pi", UnifiedPush.EXTRA_PI)
        assertEquals("unifiedpush://link", UnifiedPush.LINK)
        assertEquals(4, UnifiedPush.CONNECTOR_ACTIONS.size)
    }

    @Test
    fun `an envelope fits a distributor's message with room to spare`() {
        assertTrue(
            Push.ENVELOPE_LEN < UnifiedPush.MAX_MESSAGE,
            "an envelope would be truncated by a distributor",
        )
        // Asserted as a ratio rather than as "less than", because the useful
        // claim is that no future field can quietly approach the limit.
        assertTrue(Push.ENVELOPE_LEN * 20 < UnifiedPush.MAX_MESSAGE)
    }

    @Test
    fun `a token is per machine, random, and recognisable as ours`() {
        val a = UnifiedPush.newToken()
        val b = UnifiedPush.newToken()
        assertNotEquals(a, b, "two machines would share a registration")
        assertTrue(UnifiedPush.isToken(a))
        assertTrue(a.toByteArray().size <= UnifiedPush.MAX_TOKEN)
        // Base64url of 16 bytes: no padding, no characters that would need
        // escaping in an intent extra or a log line.
        assertEquals(22, a.length)
        assertNotNull(Base64Url.decode(a))
        // A token from somewhere else is not ours, so a stray broadcast for
        // another app's registration is dropped rather than acted on.
        for (bad in listOf("", "a b", "tok/en", "tok=en", "x".repeat(UnifiedPush.MAX_TOKEN + 1))) {
            assertFalse(UnifiedPush.isToken(bad), "$bad was accepted as a token")
        }
        assertFalse(UnifiedPush.isToken(null))
    }

    @Test
    fun `an endpoint is checked here as well as at the machine`() {
        assertEquals(
            "https://ntfy.sh/upAbCdEf123",
            UnifiedPush.checkEndpoint(" https://ntfy.sh/upAbCdEf123 "),
        )
        // The owner's own server on their own LAN is the privacy-maximal
        // deployment and must not be refused.
        assertNotNull(UnifiedPush.checkEndpoint("https://192.168.1.10:8443/UP?id=x"))
        for (bad in listOf(
            null,
            "",
            "http://ntfy.sh/up1",
            "ntfy.sh/up1",
            "https://",
            "https://user:pw@ntfy.sh/up",
            "https://ntfy.sh/up#frag",
            "https://ntfy.sh/up with space",
            "https://ntfy.sh/up\nX: y",
            "https://ntfy.sh/" + "u".repeat(UnifiedPush.MAX_ENDPOINT),
        )) {
            assertNull(UnifiedPush.checkEndpoint(bad), "$bad was accepted as an endpoint")
        }
    }

    @Test
    fun `a registration failure says which distributor and what to do`() {
        // "Registration failed" on its own is the message that makes somebody
        // reinstall the app to fix a distributor that is not signed in.
        val vapid = UnifiedPush.Failure(UnifiedPush.REASON_VAPID_REQUIRED).explain("ntfy")
        assertTrue(vapid.contains("ntfy"))
        assertTrue(vapid.contains("VAPID"))
        assertFalse(UnifiedPush.Failure(UnifiedPush.REASON_VAPID_REQUIRED).isTransient)

        val network = UnifiedPush.Failure(UnifiedPush.REASON_NETWORK)
        assertTrue(network.isTransient, "a network failure is the only one waiting fixes")
        assertTrue(network.explain("ntfy").contains("ntfy"))

        assertFalse(UnifiedPush.Failure(UnifiedPush.REASON_ACTION_REQUIRED).isTransient)
        assertFalse(UnifiedPush.Failure(null).isTransient)
        for (reason in listOf(
            UnifiedPush.REASON_INTERNAL_ERROR,
            UnifiedPush.REASON_ACTION_REQUIRED,
            null,
            "SOMETHING_NEW",
        )) {
            assertTrue(UnifiedPush.Failure(reason).explain("ntfy").contains("ntfy"))
        }
    }

    @Test
    fun `a message carrying an id is acknowledged and one without is not`() {
        // A missed acknowledgement does not lose THIS message; it can lose the
        // ENDPOINT, because a distributor may drop one whose acknowledgement
        // never arrives. That is a failure nobody would connect to its cause.
        assertEquals("abc", UnifiedPush.ackFor("abc"))
        assertNull(UnifiedPush.ackFor(null))
        assertNull(UnifiedPush.ackFor(""))
        assertNull(UnifiedPush.ackFor("x".repeat(UnifiedPush.MAX_TOKEN + 1)))
    }

    @Test
    fun `the request the phone sends names no device and carries the key once`() {
        val line = Agentd.pushRegister("https://ntfy.sh/upA", "AAAA")
        assertTrue(line.contains(""""cmd":"push_register""""))
        assertTrue(line.contains(""""endpoint":"https://ntfy.sh/upA""""))
        assertTrue(line.contains(""""key":"AAAA""""))
        // A device field could only be a way to redirect somebody else's
        // notifications; the far end binds the registration to the handshake.
        assertFalse(line.contains("device"))
        assertEquals("""{"cmd":"push_unregister"}""", Agentd.pushUnregister())
        // An endpoint with a quote in it must not be able to end the JSON
        // string and add a field.
        assertFalse(Agentd.pushRegister("https://x/\",\"cmd\":\"run", "k").contains("""","cmd":"run"""))
    }

    @Test
    fun `a machine too old to push is recognised rather than reported as broken`() {
        // An older apex-remoted forwards push_register to apex-agentd, which
        // does not know the verb. The phone must read that as "poll only",
        // because it is not a fault and nothing is wrong with the pairing.
        val tooOld = AgentError(
            "bad_request",
            "unparseable request: unknown variant `push_register`, expected one of `hello`, `list`",
        )
        assertTrue(Agentd.isTooOld(tooOld))
        assertFalse(Agentd.isTooOld(AgentError("bad_request", "a push key is 32 bytes; this one is 3")))
        assertFalse(Agentd.isTooOld(AgentError("permission_denied", "unknown variant")))
    }

    private fun assertNotNull(value: Any?) = assertTrue(value != null)

    // ── the rule that decides whether a machine is told anything ────────────

    private fun paired(push: PushRegistration?) = PairedMachine(
        deviceId = "0123456789abcdef",
        machine = "katana",
        desktopKey = "AAAA",
        deviceKey = "BBBB",
        sealed = "CCCC",
        pairedMs = 1,
        push = push,
    )

    private fun registration(
        endpoint: String,
        sent: String = "",
    ) = PushRegistration(token = "tok", endpoint = endpoint, key = "AAAA", sentEndpoint = sent)

    @Test
    fun `a machine is told an endpoint exactly once, and again when it rotates`() {
        // This is the whole wiring rule, and every branch of it is a failure
        // that is SILENT on a phone: too eager and every reconnection spends a
        // round trip re-registering; too lazy and the machine never learns
        // where to post, so nothing ever arrives and nothing says why.
        val e = "https://ntfy.sh/upAbCdEf"

        // Never asked a distributor: nothing to say.
        assertNull(Push.endpointToSend(paired(null)))
        // Asked, and the distributor has not answered yet. Empty is a real
        // state and not an error.
        assertNull(Push.endpointToSend(paired(registration(""))))
        // An endpoint that could not be posted to is refused HERE rather than
        // by the machine, so the phone does not burn a round trip to be told
        // what it could see. Same rules as `push.rs`'s `Endpoint::parse`.
        assertNull(Push.endpointToSend(paired(registration("http://ntfy.sh/upA"))))
        assertNull(Push.endpointToSend(paired(registration("https://ntfy.sh/up A"))))

        // The first real one: sent.
        assertEquals(e, Push.endpointToSend(paired(registration(e))))

        // Already told. The ordinary case on every reconnection after the
        // first, and the one that must cost nothing.
        assertNull(Push.endpointToSend(paired(registration(e, sent = e))))

        // The distributor rotated it. `endpoint` moved and `sentEndpoint` did
        // not, which is the only way the two states are distinguishable — with
        // one field they are the same value and a rotation is never sent.
        val rotated = "https://ntfy.sh/upZzZzZz"
        assertEquals(rotated, Push.endpointToSend(paired(registration(rotated, sent = e))))
    }

    @Test
    fun `the line a machine is told carries exactly the endpoint that was chosen`() {
        // The join between the decision above and the wire: `MachineLink`
        // builds the line from what `endpointToSend` returned, so a phone that
        // decided to send the rotated endpoint cannot send the old one.
        val rotated = "https://ntfy.sh/upZzZzZz"
        val machine = paired(registration(rotated, sent = "https://ntfy.sh/upAbCdEf"))
        val endpoint = requireNotNull(Push.endpointToSend(machine))
        val line = Agentd.pushRegister(endpoint, machine.push!!.key)
        assertTrue(line.contains(""""endpoint":"$rotated""""))
        assertFalse(line.contains("upAbCdEf"))
    }

    @Test
    fun `a registration remembers which distributor carries it`() {
        // Acknowledgements go to the app that delivered the message, and
        // Android does not say which app sent a broadcast. On a phone with two
        // distributors installed the stored name is the only correct answer;
        // guessing costs the ENDPOINT after thirty seconds, days before
        // anybody notices notifications stopped.
        val r = PushRegistration(
            token = "tok",
            endpoint = "https://ntfy.sh/upA",
            key = "AAAA",
            distributor = "io.heckel.ntfy",
        )
        assertEquals("io.heckel.ntfy", r.distributor)
        // Default empty, so a record written before this field existed still
        // parses and falls back to the guess it used to make.
        assertEquals("", registration("https://ntfy.sh/upA").distributor)
    }

    @Test
    fun `a stored registration never prints its key`() {
        // `PairedMachine.toString` redacts for the same reason; this record
        // reaches logcat through the same paths.
        val text = registration("https://ntfy.sh/upA").copy(key = "s3cr3tKeyMaterial").toString()
        assertFalse(text.contains("s3cr3tKeyMaterial"))
        assertTrue(text.contains("https://ntfy.sh/upA"))
    }
}
