#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  generate-signing-key.sh — make the key that every APEX Remote release is
#  signed with, once, on your own machine.
#
#      android/tools/generate-signing-key.sh
#
#  That is the whole command. It takes about a minute, it asks nothing, and it
#  prints what to do next.
#
#  WHY THIS IS NOT A CI JOB. A key generated by a workflow has its only origin
#  inside a system neither you nor anyone reading this controls end to end.
#  Generation happens once, and it should happen where the operator is, on a
#  machine whose disk you can point at. CI gets a copy afterwards, and a copy
#  is all it ever gets.
#
#  WHAT YOU END UP WITH, in one directory:
#
#      release.jks        the key. Losing this is unrecoverable — see below.
#      password.txt       the password to it, 0600. The keystore without this
#                         file is scrap metal, so they are backed up together.
#      keystore.base64    the same keystore, base64, ready for GitHub.
#      BACKUP-README.txt  what this is and what it costs to lose, written next
#                         to it so the person who finds it in five years does
#                         not have to guess.
#
#  AND WHY THE BACKUP MATTERS MORE THAN THE KEY. A GitHub secret CANNOT BE READ
#  BACK. Once set it is write-only to everybody, including you. So if this
#  directory is lost, GitHub keeps signing releases perfectly well with a key
#  you can never retrieve — it has the shape of a backup without being one. The
#  day that copy is also lost, or the day you need to sign anything outside
#  Actions, every APEX Remote install in the world becomes un-upgradable:
#  Android accepts an update only from the key that signed what is installed,
#  and the owner's only escape is to uninstall, which destroys their paired
#  device key and their agent history.
#
#  So: this directory goes to two places that are NOT GitHub, and at least one
#  of them is not network-attached.
#
#  Options, none of which you normally need:
#      --out DIR       where to write it (default: ~/apex-android-signing)
#      --alias NAME    the key alias (default: apex-release)
#      --dname STRING  the certificate subject
#      --repo DIR      the checkout whose published fingerprint to update
#                      (default: the one this script lives in)
#      --no-pin        do not publish the fingerprint at all
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

fatal() { echo "" >&2; echo "FATAL: $*" >&2; exit 1; }
say()   { printf '%s\n' "$*"; }

out=""; alias_name="apex-release"; dname="CN=APEX-OS, O=APEX-OS, C=AU"
repo=""; write_pin=1
while [ $# -gt 0 ]; do
    case "$1" in
        --out)      out="${2:?--out needs a value}"; shift 2 ;;
        --alias)    alias_name="${2:?--alias needs a value}"; shift 2 ;;
        --dname)    dname="${2:?--dname needs a value}"; shift 2 ;;
        --repo)     repo="${2:?--repo needs a value}"; shift 2 ;;
        --no-pin)   write_pin=0; shift ;;
        -h|--help)  sed -n '2,50p' "$0"; exit 0 ;;
        *) echo "FATAL: unknown argument '$1'" >&2; exit 2 ;;
    esac
done

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
android=$(dirname "$here")
[ -n "$repo" ] || repo=$(dirname "$android")
pin_file="$repo/android/signing-certificate.sha256"
[ -n "$out" ] || out="$HOME/apex-android-signing"

# ── This does not run in CI ──────────────────────────────────────────────────
#
# Not a style preference. A key generated on a runner exists first inside a
# system whose disks, snapshots and logs are somebody else's, and the operator
# who is supposed to be keeping the only authoritative copy never had it.
if [ "${GITHUB_ACTIONS:-}" = "true" ] || [ "${CI:-}" = "true" ]; then
    fatal "this generates a signing key and must not run in CI. The key is generated once, on Andre's machine, and GitHub gets a copy. See docs/android-signing.md."
fi

# ── Where it must not be written ─────────────────────────────────────────────
case "$out" in
    /tmp/*|/tmp|/dev/shm/*|/dev/shm)
        fatal "$out is a tmpfs — it is RAM, and it is gone at the next reboot. That is the one property a signing key must not have." ;;
esac
if [ -e "$out/release.jks" ]; then
    fatal "$out/release.jks already exists. Generating over the top of an existing key would strand every install signed by it. If you mean to ROTATE, that is a different procedure and it needs the old key: docs/android-signing.md."
fi
mkdir -p "$out" || fatal "cannot create $out"
out=$(cd "$out" && pwd)
# A key inside a repository is a key for everybody who can clone it, and
# `git add -A` is one keystroke.
if git -C "$out" rev-parse --show-toplevel >/dev/null 2>&1; then
    top=$(git -C "$out" rev-parse --show-toplevel)
    fatal "$out is inside the git repository at $top. A signing key in a repository is a signing key for everyone who can clone it. Choose a directory outside any checkout with --out."
fi

# ── The tools, proved rather than assumed ────────────────────────────────────
#
# On this laptop /usr/lib/jvm/java-21-openjdk/conf is a dangling symlink, so
# that JDK's keytool dies with "Error loading java.security file" — which reads
# like a broken keystore rather than a broken JDK. So keytool is not merely
# found, it is RUN before it is trusted, and the alternatives are tried.
find_keytool() {
    local cand
    for cand in ${JAVA_HOME:+"$JAVA_HOME/bin/keytool"} "$(command -v keytool 2>/dev/null || true)" \
                /usr/lib/jvm/*/bin/keytool; do
        [ -n "$cand" ] && [ -x "$cand" ] || continue
        "$cand" -help >/dev/null 2>&1 && { printf '%s' "$cand"; return 0; }
    done
    return 1
}
KEYTOOL=$(find_keytool) \
    || fatal "no working keytool was found. Install a JDK (dnf install java-21-openjdk-headless) or set JAVA_HOME to one that works."
command -v openssl  >/dev/null 2>&1 || fatal "openssl is required to generate the password"
command -v python3  >/dev/null 2>&1 || fatal "python3 is required to publish the fingerprint in the docs"
command -v base64   >/dev/null 2>&1 || fatal "base64 is required"
command -v sha256sum >/dev/null 2>&1 || fatal "sha256sum is required"

say "keytool:   $KEYTOOL"
say "directory: $out"
say ""

# ── The password ─────────────────────────────────────────────────────────────
#
# Generated, not chosen: this password is never typed by a human, it is pasted
# once into a GitHub secret and otherwise read out of a file, so there is no
# reason for it to be memorable and every reason for it to be 96 bits.
#
# Hex on purpose. A base64 password containing `+` or `/` survives everything
# here, but it is the kind of value that gets mangled once by something else's
# quoting and costs an afternoon.
#
# It is NEVER PRINTED. Terminal scrollback is a file too, and this one is
# recorded in an agent transcript. It goes to a 0600 file and stays there.
umask 077
pw_file="$out/password.txt"
printf '%s' "$(openssl rand -hex 24)" > "$pw_file" || fatal "cannot write $pw_file"
chmod 600 "$pw_file"
# No trailing newline, above, and this is why: `gh secret set NAME < file`
# stores the bytes it is given. A trailing newline becomes part of the
# password, the keystore then refuses to open, and the error you get says the
# password is wrong — which it is, invisibly.

# ── The key ──────────────────────────────────────────────────────────────────
#
# RSA 4096. Android requires RSA or DSA/EC for APK signing; 4096 is what an
# upload key that must outlive the project should be, and the cost is
# milliseconds per build.
#
# 10950 days is thirty years. An APK cannot be updated once its signing
# certificate has expired, so the certificate has to outlive the app; Google
# Play's own rule is an expiry after 22 October 2033 for exactly this reason.
#
# -storepass:file, never -storepass <value>: an argument is visible in `ps` to
# every process on the machine, including anything else running as you.
#
# PKCS12 is keytool's default store type and the one this project expects.
# MEASURED, not assumed: a PKCS12 keystore cannot hold a key password that
# differs from the store password — keytool says
#   "Different store and key passwords not supported for PKCS12 KeyStores"
# and ignores the one you gave it. That is why APEX_KEY_PASSWORD and
# APEX_KEYSTORE_PASSWORD below are the same value, and it is not an oversight.
ks="$out/release.jks"
if ! "$KEYTOOL" -genkeypair \
        -storetype PKCS12 \
        -keystore "$ks" \
        -alias "$alias_name" \
        -keyalg RSA -keysize 4096 \
        -validity 10950 \
        -dname "$dname" \
        -storepass:file "$pw_file" 2>"$out/.keytool.err"; then
    say ""
    sed -n '1,20p' "$out/.keytool.err" >&2
    rm -f "$out/.keytool.err"
    fatal "keytool could not generate the key. Nothing was written that you need to keep."
fi
rm -f "$out/.keytool.err"
chmod 600 "$ks"

# ── Read it back ─────────────────────────────────────────────────────────────
#
# keytool exiting 0 is not evidence the keystore opens with the password we
# just wrote. This is the same rule the release workflow follows when it reads
# a release back after creating it.
der="$out/.cert.der"
if ! "$KEYTOOL" -exportcert -keystore "$ks" -alias "$alias_name" \
        -storepass:file "$pw_file" > "$der" 2>/dev/null; then
    rm -f "$der"
    fatal "the keystore was written but does not open with the password that was just generated. Nothing here should be kept; delete $out and run this again."
fi
[ -s "$der" ] || { rm -f "$der"; fatal "the exported certificate is empty"; }
sum=$(sha256sum "$der") || fatal "sha256sum failed"
fingerprint="${sum%% *}"
rm -f "$der"

base64 -w0 < "$ks" > "$out/keystore.base64" 2>/dev/null || base64 < "$ks" | tr -d '\n' > "$out/keystore.base64"
[ -s "$out/keystore.base64" ] || fatal "could not base64 the keystore"
chmod 600 "$out/keystore.base64"

# ── The fingerprint goes in the repository ───────────────────────────────────
#
# Public value, public file. It is what lets a stranger check what signed the
# APK they downloaded, and what lets the release refuse a keystore that is not
# this one.
#
# The docs and the README carry the same value between markers, and it is
# written HERE rather than left for a person to copy, because a fingerprint
# published in three places and updated in one is worse than a fingerprint
# published in none: two of the three then tell a user their APK was signed by
# the wrong key. `tests/test-android-signing.sh` fails if they disagree.
pin_written=0; updated=()
if [ "$write_pin" = 1 ]; then
    if [ -f "$pin_file" ]; then
        {
            # Keep the file's own explanation, drop whatever value was there.
            grep '^#' "$pin_file"
            printf '%s\n' "$fingerprint"
        } > "$pin_file.new" && mv "$pin_file.new" "$pin_file" && pin_written=1
    else
        mkdir -p "$(dirname "$pin_file")"
        printf '%s\n' "$fingerprint" > "$pin_file" && pin_written=1
    fi
    chmod 644 "$pin_file" 2>/dev/null || true
    [ "$pin_written" = 1 ] || fatal "could not write $pin_file"

    for doc in "$repo/README.md" "$repo"/docs/*.md; do
        [ -f "$doc" ] || continue
        grep -q 'fingerprint:begin' "$doc" 2>/dev/null || continue
        APEX_FP="$fingerprint" python3 - "$doc" <<'PY' || fatal "could not update the fingerprint in $doc"
import os, re, sys
path = sys.argv[1]
fp = os.environ["APEX_FP"]
text = open(path, encoding="utf-8").read()
new, n = re.subn(
    r"(<!-- fingerprint:begin -->\n).*?(\n<!-- fingerprint:end -->)",
    lambda m: m.group(1) + fp + m.group(2),
    text,
    flags=re.S,
)
if n == 0:
    # A begin marker with no end is a half-edited file, and silently leaving
    # the old value there is the failure this block exists to prevent.
    raise SystemExit("no complete fingerprint:begin/end block in " + path)
open(path, "w", encoding="utf-8").write(new)
PY
        updated+=("$doc")
    done
fi

cat > "$out/BACKUP-README.txt" <<BACKUP
APEX Remote — Android release signing key
=========================================

Generated: $(date -Is)
Alias:     $alias_name
Subject:   $dname
SHA-256 certificate fingerprint:
    $fingerprint

WHAT THIS IS

  release.jks     the private key every published APEX Remote APK is signed
                  with, plus its self-signed certificate.
  password.txt    the password to it. The keystore is useless without this
                  file, so the two are ONE backup unit, never separated.
  keystore.base64 release.jks, base64, as it is stored in the GitHub secret
                  APEX_KEYSTORE_BASE64.

WHAT IT COSTS TO LOSE IT

  Android will install an update only if it is signed by the same key as the
  version already installed. Lose this key and every APEX Remote install in
  the world is frozen: the only way for an owner to move to a newer build is
  to uninstall, and uninstalling destroys the phone's paired device key and
  its history. There is no server-side fix and no appeal.

  GITHUB IS NOT A BACKUP OF THIS. A GitHub secret cannot be read back — once
  set it is write-only to everybody, including the person who set it. The copy
  in the repository's secrets will keep signing releases long after this
  directory is gone, and it can never be retrieved.

  So this directory lives in at least two places that are not GitHub, and at
  least one of them is not network-attached.

WHILE IT STILL EXISTS, IT CAN BE ROTATED

  \`apksigner rotate\` produces a SigningCertificateLineage that lets a NEW key
  take over from this one, and this app already enables the v3 signature that
  carries it. That works only while this key still exists. The procedure is in
  docs/android-signing.md of the apex-os repository — read it before you need
  it, because after this key is lost it is worth nothing.
BACKUP
chmod 600 "$out/BACKUP-README.txt"

say "──────────────────────────────────────────────────────────────────────────"
say "The key exists. It is in $out and nowhere else."
say ""
say "  certificate SHA-256 fingerprint:"
say "    $fingerprint"
say ""
if [ "$pin_written" = 1 ]; then
    say "  published in:"
    say "    ${pin_file#"$repo"/}"
    for doc in ${updated[@]+"${updated[@]}"}; do say "    ${doc#"$repo"/}"; done
    say ""
    paths="${pin_file#"$repo"/}"
    for doc in ${updated[@]+"${updated[@]}"}; do paths="$paths ${doc#"$repo"/}"; done
    say "  Commit them:"
    say "    git -C $repo add $paths"
    say "    git -C $repo commit -m 'feat(android): publish the release signing certificate fingerprint'"
    say ""
    say "  Until that is committed AND the secrets below are set, the release"
    say "  workflow refuses to build. That is deliberate."
else
    say "  (nothing was published; --no-pin was given)"
fi
say ""
say "1. BACK IT UP FIRST, before anything else."
say ""
say "     $out"
say ""
say "   All four files, together. The keystore without password.txt is scrap."
say "   Two places that are not GitHub, one of them not network-attached."
say "   GitHub CANNOT hold the backup: a secret cannot be read back, by anyone,"
say "   ever — including you. The copy there will go on signing releases that"
say "   you can never retrieve, which looks like redundancy and is not."
say ""
say "2. Then give GitHub its working copy. Four secrets, read from files so"
say "   that no password is ever typed into a shell and into its history:"
say ""
say "     gh secret set APEX_KEYSTORE_BASE64   -R AndreNijman/apex-os < $out/keystore.base64"
say "     gh secret set APEX_KEYSTORE_PASSWORD -R AndreNijman/apex-os < $pw_file"
say "     gh secret set APEX_KEY_PASSWORD      -R AndreNijman/apex-os < $pw_file"
say "     printf '%s' '$alias_name' | gh secret set APEX_KEY_ALIAS -R AndreNijman/apex-os"
say ""
say "   APEX_KEY_PASSWORD is the same value as APEX_KEYSTORE_PASSWORD on"
say "   purpose: a PKCS12 keystore cannot have two different passwords."
say ""
say "3. Check they arrived — the names are readable even though the values are"
say "   not, which is the whole point:"
say ""
say "     gh secret list -R AndreNijman/apex-os"
say ""
say "4. Then a dry run before any real release:"
say ""
say "     gh workflow run release-android.yml -R AndreNijman/apex-os -f dry_run=true"
say ""
say "The password is NOT printed here on purpose. It is in $pw_file."
say "──────────────────────────────────────────────────────────────────────────"
