-- ─────────────────────────────────────────────────────────────────────────────
--  APEX-OS — default Hyprland config (seeded per-user by apex-shell-firstrun).
--  Replaces the hyprlang hyprland.conf: Hyprland 0.55 deprecated hyprlang for
--  Lua and gave it "1-2 releases starting from 0.55" to live. This image ships
--  0.56.2, so the old config had one release of headroom left.
--
--  APEX Shell (Quickshell) draws the bar/UI; this file owns the compositor,
--  autostart and keybinds. Keybinds trigger APEX Shell popups over its IPC.
--
--  It is your file now, edits here persist. `apex-hypr-migrate` never rewrites
--  a hyprland.lua that already exists.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── How the APEX modules are found ───────────────────────────────────────────
-- Hyprland PREPENDS the directory holding this file to `package.path` before it
-- runs it. Verified against the shipped 0.56.2, which reports:
--
--     ~/.config/hypr/?.lua;~/.config/hypr/?/init.lua;/usr/share/lua/5.4/?.lua;…
--
-- so `require("apex.appearance")` resolves to ~/.config/hypr/apex/appearance.lua
-- with no `package.path` edit and no `dofile` with an absolute path. That is
-- also why nothing in this tree needs the seed-time @HOME@ substitution the
-- hyprlang config needed for its `source =` lines: there are no absolute paths
-- left to substitute.
--
-- ── Why the loader, and not a bare `require` ─────────────────────────────────
-- A `require` of a missing module RAISES, and an uncaught error aborts the whole
-- config — every hl.* call after it is skipped. That is the same trap the old
-- `source =` had (a missing file was a fatal config error), except worse,
-- because it also takes out everything below it.
--
-- Three of the modules are GENERATED and legitimately absent until their
-- generator has run once, so:
--
--   * absent            → skipped in silence, it is not an error yet;
--   * present, broken   → recorded, and every other module still loads;
--   * anything recorded → re-raised at the very END of this file, so
--                         `hyprctl configerrors` still reports it.
--
-- Losing the whole desktop because a settings page wrote one bad line is the
-- failure this shape exists to prevent.

local failures = {}

-- Drop any cached apex.* module so `hyprctl reload` re-reads the generated
-- files rather than serving what was on disk at login. Done ONCE, here, rather
-- than per-load: within a single config pass the cache is what lets
-- apex/shell-keybinds.lua share the handle table apex/keybindings.lua returns
-- instead of executing it a second time and double-binding every default.
for name in pairs(package.loaded) do
    if name:sub(1, 5) == "apex." then package.loaded[name] = nil end
end

local function apex(name)
    local module = "apex." .. name
    if not package.searchpath(module, package.path) then
        return nil          -- generated, not written yet
    end
    local ok, result = pcall(require, module)
    if ok then return result end
    failures[#failures + 1] = ("apex/%s.lua: %s"):format(name, tostring(result))
    return nil
end

-- ── Load order is the override order ─────────────────────────────────────────
-- `hl.config` is last-write-wins (verified: two calls setting input.kb_layout
-- leave `hl.get_config("input.kb_layout")` reporting the second). So the static
-- APEX defaults load FIRST and the generated files load LAST, which is what
-- makes a value chosen in APEX Settings beat the shipped default — the same
-- ordering the hyprlang config got from putting its `source =` lines at the
-- bottom.
--
-- It also means a broken generated module cannot take the defaults down with
-- it: by the time it fails, they are already applied.

apex("appearance")        -- look and feel, animations
apex("session")           -- environment variables, autostart
apex("input-defaults")    -- keyboard layout and input fallbacks
apex("monitors-default")  -- the catch-all monitor rule
apex("rules")             -- window rules
apex("keybindings")       -- APEX keybinds; returns handles the shell can disable

apex("monitors")        -- generated by apex-display-apply   (Settings → Display)
apex("input")           -- generated by apex-input-apply     (Settings → Input)
apex("shell-keybinds")  -- generated by APEX Shell           (Settings → Keybinds)

-- Written once by apex-hypr-migrate, from a hyprland.conf this machine used to
-- have. Absent on a machine that never had one. Loaded LAST, after the
-- generated modules, on purpose: everything in it is a line the user typed by
-- hand, and a generator default should not quietly take it back.
apex("user-overrides")

-- ── Your own configuration goes here ─────────────────────────────────────────
-- Anything below this line survives: nothing in APEX rewrites this file after
-- it has been seeded. The API is documented at
-- https://wiki.hypr.land/Configuring/Start/ and, authoritatively for the
-- version installed right now, in /usr/share/hypr/stubs/hl.meta.lua.
--
--     hl.bind("SUPER + G", hl.dsp.exec_cmd("gimp"))
--     hl.config({ general = { gaps_out = 20 } })
--
-- To turn off an APEX default rather than shadow it, take its handle:
--
--     require("apex.keybindings").disable("SUPER", "T")

-- ── Report anything that failed to load ──────────────────────────────────────
-- Deliberately the LAST statement in the file: raising here means every module
-- that could load has already applied, and `hyprctl configerrors` still names
-- the one that could not.
if #failures > 0 then
    error("APEX config modules failed to load:\n  " .. table.concat(failures, "\n  "), 0)
end
