package com.apexos.remote.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * The bytes `snow` puts on the wire, read back.
 *
 * Generated by `apexd/apex-remote-core/src/vectors.rs`, which also has a test
 * asserting the committed file is still what `snow` produces. Neither half is
 * worth anything alone: without the Rust check this file could drift from the
 * protocol the desktop speaks, and without the Kotlin replay the Rust check is
 * testing `snow` against itself.
 */
object Vectors {
    private val root: JsonObject by lazy {
        val text = Vectors::class.java.getResourceAsStream("/noise-vectors.json")
            ?.bufferedReader()?.readText()
            ?: error(
                "noise-vectors.json is missing; generate it with `cargo test -p apex-remote-core " +
                    "-- --ignored write_the_android_noise_vectors`",
            )
        Json.parseToJsonElement(text).jsonObject
    }

    fun hex(field: String): ByteArray = decodeHex(root[field]!!.jsonPrimitive.content)

    fun version(): Int = root["protocol_version"]!!.jsonPrimitive.content.toInt()

    /** A plain string field, such as the rendezvous id or a base64url key. */
    fun text(field: String): String = root[field]!!.jsonPrimitive.content

    fun pattern(which: String): JsonObject = root[which]!!.jsonObject

    fun patternHex(which: String, field: String): ByteArray =
        decodeHex(pattern(which)[field]!!.jsonPrimitive.content)

    fun transport(which: String): JsonArray = pattern(which)["transport"]!!.jsonArray

    fun decodeHex(text: String): ByteArray {
        require(text.length % 2 == 0) { "a hex string has an even length" }
        return ByteArray(text.length / 2) {
            ((hexDigit(text[it * 2]) shl 4) or hexDigit(text[it * 2 + 1])).toByte()
        }
    }

    fun encodeHex(bytes: ByteArray): String =
        bytes.joinToString("") { "%02x".format(it.toInt() and 0xff) }

    private fun hexDigit(c: Char): Int = when (c) {
        in '0'..'9' -> c - '0'
        in 'a'..'f' -> c - 'a' + 10
        in 'A'..'F' -> c - 'A' + 10
        else -> error("'$c' is not a hex digit")
    }
}
