//! Byte vectors for the Android client, generated by `snow` and checked here.
//!
//! ## Why this module exists in shipped code
//!
//! The Android app cannot use `snow`. Nothing equivalent exists for Kotlin
//! that is worth trusting, so `android/core` writes the two patterns out over
//! BouncyCastle's primitives — and a hand-rolled Noise that is only ever
//! tested against itself will interoperate with itself and with nothing else.
//! Every mistake that matters (the nonce's endianness, HKDF without an `info`
//! field, whether the protocol name is padded or hashed, which of the split
//! keys is the sending one) produces a second implementation that is perfectly
//! self-consistent and cannot talk to this one.
//!
//! So: fixed statics, fixed ephemerals, and the exact bytes `snow` puts on the
//! wire, written to `android/core/src/test/resources/noise-vectors.json`. The
//! Kotlin tests replay them and must produce the same bytes; the test below
//! regenerates them and must find the committed file unchanged. A protocol
//! change therefore turns BOTH suites red, which is the only arrangement in
//! which the file is evidence rather than decoration.
//!
//! Nothing here is reachable from a running `apex-remoted`: it is a test
//! module, compiled only under `cfg(test)`.

#![cfg(test)]

use snow::params::NoiseParams;
use snow::Builder;

use crate::REMOTE_PROTOCOL_VERSION as V;

/// Deterministic and arbitrary. Any 32 bytes is a valid X25519 scalar — both
/// implementations clamp at use — so these are chosen only to be obviously
/// fixed rather than obviously random.
const DESKTOP_SECRET: [u8; 32] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31,
];
const DEVICE_SECRET: [u8; 32] = [
    32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
    56, 57, 58, 59, 60, 61, 62, 63,
];
const INITIATOR_EPHEMERAL: [u8; 32] = [
    64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
    88, 89, 90, 91, 92, 93, 94, 95,
];
const RESPONDER_EPHEMERAL: [u8; 32] = [
    96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
    116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
];

/// The pairing payload, byte for byte as the app will build it.
///
/// A real `PairingRequest` and not a placeholder, so the vector also pins the
/// JSON field names and their order — a Kotlin client that serialised
/// `user_verification` as `userVerification` would encrypt a different
/// plaintext and produce a different ciphertext, and this is where that shows
/// up rather than on a phone.
fn pairing_payload() -> Vec<u8> {
    let request = crate::pairing::PairingRequest {
        key: crate::b64_encode(&public_of(&DEVICE_SECRET)),
        name: "pixel-8".into(),
        token: crate::b64_encode(&[7u8; crate::pairing::TOKEN_BYTES]),
        user_verification: true,
    };
    serde_json::to_vec(&request).expect("a pairing request serialises")
}

fn public_of(secret: &[u8; 32]) -> [u8; 32] {
    crate::noise::public_from_secret(secret).expect("a public key")
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn params(name: &str) -> NoiseParams {
    name.parse().expect("a pattern constant parses")
}

/// One completed handshake plus some transport traffic, as JSON.
fn generate() -> String {
    let prologue = crate::noise::prologue(V);
    let desktop_public = public_of(&DESKTOP_SECRET);
    let device_public = public_of(&DEVICE_SECRET);

    // ---- Noise_NK, the pairing handshake -------------------------------
    let mut dev = Builder::new(params(crate::noise::PAIRING_PATTERN))
        .prologue(&prologue)
        .remote_public_key(&desktop_public)
        .fixed_ephemeral_key_for_testing_only(&INITIATOR_EPHEMERAL)
        .build_initiator()
        .expect("NK initiator");
    let mut desk = Builder::new(params(crate::noise::PAIRING_PATTERN))
        .prologue(&prologue)
        .local_private_key(&DESKTOP_SECRET)
        .fixed_ephemeral_key_for_testing_only(&RESPONDER_EPHEMERAL)
        .build_responder()
        .expect("NK responder");

    let nk_m1_payload = pairing_payload();
    let mut buf = vec![0u8; 65535];
    let n = dev
        .write_message(&nk_m1_payload, &mut buf)
        .expect("NK message 1");
    let nk_m1 = buf[..n].to_vec();
    let mut got = vec![0u8; 65535];
    let n = desk.read_message(&nk_m1, &mut got).expect("NK read 1");
    assert_eq!(&got[..n], &nk_m1_payload[..], "the responder read a different payload");

    let nk_m2_payload =
        br#"{"ok":true,"device":"abcdefghijklmnop","machine":"l16"}"#.to_vec();
    let n = desk
        .write_message(&nk_m2_payload, &mut buf)
        .expect("NK message 2");
    let nk_m2 = buf[..n].to_vec();
    let n = dev.read_message(&nk_m2, &mut got).expect("NK read 2");
    assert_eq!(&got[..n], &nk_m2_payload[..]);

    let mut dev_t = dev.into_transport_mode().expect("NK transport");
    let mut desk_t = desk.into_transport_mode().expect("NK transport");
    let nk_transport = transport_samples(&mut dev_t, &mut desk_t);

    // ---- Noise_IK, the session handshake -------------------------------
    let mut dev = Builder::new(params(crate::noise::SESSION_PATTERN))
        .prologue(&prologue)
        .local_private_key(&DEVICE_SECRET)
        .remote_public_key(&desktop_public)
        .fixed_ephemeral_key_for_testing_only(&INITIATOR_EPHEMERAL)
        .build_initiator()
        .expect("IK initiator");
    let mut desk = Builder::new(params(crate::noise::SESSION_PATTERN))
        .prologue(&prologue)
        .local_private_key(&DESKTOP_SECRET)
        .fixed_ephemeral_key_for_testing_only(&RESPONDER_EPHEMERAL)
        .build_responder()
        .expect("IK responder");

    // Empty, which is what `apex-remoted` reads and discards. Pinned here so
    // that a client which started sending something would change these bytes.
    let n = dev.write_message(&[], &mut buf).expect("IK message 1");
    let ik_m1 = buf[..n].to_vec();
    desk.read_message(&ik_m1, &mut got).expect("IK read 1");
    assert_eq!(
        desk.get_remote_static(),
        Some(&device_public[..]),
        "IK did not carry the device's static key"
    );

    // The machine name, as raw bytes and not JSON: `serve.rs` writes
    // `state.machine.as_bytes()`.
    let ik_m2_payload = b"l16".to_vec();
    let n = desk
        .write_message(&ik_m2_payload, &mut buf)
        .expect("IK message 2");
    let ik_m2 = buf[..n].to_vec();
    let n = dev.read_message(&ik_m2, &mut got).expect("IK read 2");
    assert_eq!(&got[..n], &ik_m2_payload[..]);

    let mut dev_t = dev.into_transport_mode().expect("IK transport");
    let mut desk_t = desk.into_transport_mode().expect("IK transport");
    let ik_transport = transport_samples(&mut dev_t, &mut desk_t);

    serde_json::to_string_pretty(&serde_json::json!({
        "note": "Generated by apexd/apex-remote-core/src/vectors.rs from snow. \
                 Do not edit by hand; run the writer test to regenerate.",
        "protocol_version": V,
        "prologue_hex": hex(&prologue),
        "desktop_secret_hex": hex(&DESKTOP_SECRET),
        "desktop_public_hex": hex(&desktop_public),
        // Not part of a handshake, but derived from the same pinned key and
        // by a rule the device has to reproduce exactly or it meets nobody.
        "rendezvous_id": crate::rendezvous::rendezvous_id(&desktop_public),
        "device_id": crate::device::Device::id_for(&crate::b64_encode(&device_public)),
        "desktop_key_b64": crate::b64_encode(&desktop_public),
        "device_key_b64": crate::b64_encode(&device_public),
        "device_secret_hex": hex(&DEVICE_SECRET),
        "device_public_hex": hex(&device_public),
        "initiator_ephemeral_hex": hex(&INITIATOR_EPHEMERAL),
        "responder_ephemeral_hex": hex(&RESPONDER_EPHEMERAL),
        "nk": {
            "pattern": crate::noise::PAIRING_PATTERN,
            "m1_payload_hex": hex(&nk_m1_payload),
            "m1_hex": hex(&nk_m1),
            "m2_payload_hex": hex(&nk_m2_payload),
            "m2_hex": hex(&nk_m2),
            "transport": nk_transport,
        },
        "ik": {
            "pattern": crate::noise::SESSION_PATTERN,
            "m1_payload_hex": "",
            "m1_hex": hex(&ik_m1),
            "m2_payload_hex": hex(&ik_m2_payload),
            "m2_hex": hex(&ik_m2),
            "transport": ik_transport,
        },
    }))
    .expect("the vectors serialise")
        + "\n"
}

/// Four transport messages, alternating direction, so the vectors pin the
/// nonce counter's advance as well as the first message's key.
fn transport_samples(
    initiator: &mut snow::TransportState,
    responder: &mut snow::TransportState,
) -> Vec<serde_json::Value> {
    let script: [(bool, &[u8]); 4] = [
        (true, br#"{"cmd":"list"}"#),
        (false, br#"{"ok":true,"sessions":[]}"#),
        (true, b"\x1b[2K\x00\xff"),
        (false, b""),
    ];
    let mut out = Vec::new();
    let mut buf = vec![0u8; 65535];
    let mut got = vec![0u8; 65535];
    for (from_initiator, plaintext) in script {
        let (writer, reader): (&mut snow::TransportState, &mut snow::TransportState) =
            if from_initiator {
                (&mut *initiator, &mut *responder)
            } else {
                (&mut *responder, &mut *initiator)
            };
        let n = writer.write_message(plaintext, &mut buf).expect("seal");
        let sealed = buf[..n].to_vec();
        let n = reader.read_message(&sealed, &mut got).expect("open");
        assert_eq!(&got[..n], plaintext, "a transport sample did not round trip");
        out.push(serde_json::json!({
            "from": if from_initiator { "initiator" } else { "responder" },
            "plaintext_hex": hex(plaintext),
            "ciphertext_hex": hex(&sealed),
        }));
    }
    out
}

fn vectors_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../android/core/src/test/resources/noise-vectors.json")
}

/// Rewrite the committed vectors. Run deliberately:
/// `cargo test -p apex-remote-core -- --ignored write_the_android_noise_vectors`
#[test]
#[ignore = "writes a file; run deliberately after a protocol change"]
fn write_the_android_noise_vectors() {
    let path = vectors_path();
    std::fs::create_dir_all(path.parent().expect("a parent")).expect("create the resources dir");
    std::fs::write(&path, generate()).expect("write the vectors");
    eprintln!("wrote {}", path.display());
}

/// The committed file is still what `snow` produces.
///
/// This is the half that makes the vectors evidence. Without it the Kotlin
/// suite would be asserting against a file that could drift from the protocol
/// the desktop actually speaks, and the drift would be invisible until a phone
/// failed to pair.
#[test]
fn the_committed_android_vectors_are_what_snow_produces() {
    let path = vectors_path();
    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{} could not be read ({e}); regenerate it with `cargo test -p apex-remote-core -- \
             --ignored write_the_android_noise_vectors`",
            path.display()
        )
    });
    assert_eq!(
        committed,
        generate(),
        "the committed Android vectors no longer match what snow produces. If the protocol \
         changed deliberately, regenerate them with `cargo test -p apex-remote-core -- --ignored \
         write_the_android_noise_vectors` and make the Kotlin suite pass again."
    );
}
